<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wb7-input_Nachname-enz-37f-409</name>
   <tag></tag>
   <elementGuidId>53b525ac-5b4d-4c58-8c80-9f7ca1804bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div.aemf-form-container > form[name=&quot;d1074087-f2c7-4563-91c5-7695bcafa7a1&quot;] > div.form-renderer.wbx-grid-row > div.form-group.wbx-grid-col-mq1-12.wbx-grid-col-mq6-12.wbx-grid-col-offset-mq6-auto > div.form-renderer.wbx-grid-row > div.form-input-field.wbx-grid-col-mq5-6.wbx-grid-col-offset-mq5-auto.wbx-grid-col-mq6-6.wbx-grid-col-offset-mq6-auto.wbx-grid-col-mq1-12.wbx-grid-col-offset-mq1-auto.wbx-grid-col-mq3-6.wbx-grid-col-offset-mq3-auto.wbx-grid-col-mq2-12.wbx-grid-col-offset-mq2-auto > #lastnameinputfield_copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lastnameinputfield_copy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>wb7-input</value>
      <webElementGuid>4f8817b3-46a8-4764-b811-807fa386a4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastnameinputfield_copy</value>
      <webElementGuid>100e5ef4-1d64-455f-87fa-76668609e08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>hintText-lastnameinputfield_copy errorMessage-lastnameinputfield_copy</value>
      <webElementGuid>0a579c48-003a-4cff-ac47-becf21b1ba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wb-input hydrated</value>
      <webElementGuid>33fd2e08-e04e-4588-8047-6250dc08c453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>light</value>
      <webElementGuid>042dbc2b-c1d1-4e75-a33b-0b9537c81457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88f34a93-8c58-4c89-b623-640a49863a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>4746db77-faaa-4d89-8618-6a5e3a2c9b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>as</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65115098-fe13-481f-bad3-59b8b8c8107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nachname *</value>
      <webElementGuid>33561cac-9ce6-4e37-895b-2b536f93f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@class=&quot;aemf-form-container&quot;]/form[@class=&quot;aemf-form-container__form&quot;]/div[@class=&quot;form-renderer wbx-grid-row&quot;]/div[@class=&quot;form-group wbx-grid-col-mq1-12 wbx-grid-col-mq6-12 wbx-grid-col-offset-mq6-auto&quot;]/div[@class=&quot;form-renderer wbx-grid-row&quot;]/div[@class=&quot;form-input-field wbx-grid-col-mq5-6 wbx-grid-col-offset-mq5-auto wbx-grid-col-mq6-6 wbx-grid-col-offset-mq6-auto wbx-grid-col-mq1-12 wbx-grid-col-offset-mq1-auto wbx-grid-col-mq3-6 wbx-grid-col-offset-mq3-auto wbx-grid-col-mq2-12 wbx-grid-col-offset-mq2-auto&quot;]/wb7-input[@id=&quot;lastnameinputfield_copy&quot;]</value>
      <webElementGuid>65afa69f-8784-462e-a440-8e1369d15cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Mercedez/Page_Milestars I Mercedes-Benz/aemf-form-container-es-Benz-37f</value>
      <webElementGuid>5f9954a8-ab8b-4c57-87b0-0e95dbf6e59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a97db5e-5666-4251-945e-c1b681871250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>15cba459-02a1-4b34-96ba-bf0e1af14e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//wb7-input[@id = 'lastnameinputfield_copy' and @name = 'lastname']</value>
      <webElementGuid>83912bff-3e55-43a4-909a-945e53417b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
