<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wb7-button_Senden-enz-37f-16f</name>
   <tag></tag>
   <elementGuidId>a7d80eee-49c1-442a-9ea0-397138461c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Senden']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div.aemf-form-container > form[name=&quot;d1074087-f2c7-4563-91c5-7695bcafa7a1&quot;] > div.form-renderer.wbx-grid-row > div.form-formstep-cta.form-formstep-cta.wbx-grid-col-mq1-12.wbx-grid-col-mq2-12.form-formstep-cta--align-right > wb7-button.form-formstep-cta__button.wb-button.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Senden&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>wb7-button</value>
      <webElementGuid>acae033e-843b-4261-847e-577395831c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-formstep-cta__button wb-button hydrated</value>
      <webElementGuid>cd309745-0d3c-412a-9fc2-23e10691c425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f6bf1c0c-1ff6-483a-bb6c-88530ed0bebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>27b68e4e-bd7c-4397-a618-6c792dd682a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>light</value>
      <webElementGuid>9746e626-4952-4f3d-b4de-cbfabb8ecc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Senden</value>
      <webElementGuid>b8958a61-d339-49ef-bfa5-1fbab2afa372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@class=&quot;aemf-form-container&quot;]/form[@class=&quot;aemf-form-container__form&quot;]/div[@class=&quot;form-renderer wbx-grid-row&quot;]/div[@class=&quot;form-formstep-cta form-formstep-cta wbx-grid-col-mq1-12 wbx-grid-col-mq2-12 form-formstep-cta--align-right&quot;]/wb7-button[@class=&quot;form-formstep-cta__button wb-button hydrated&quot;]</value>
      <webElementGuid>0d8528f8-8115-4dfa-a541-4f242c6beea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Mercedez/Page_Milestars I Mercedes-Benz/aemf-form-container-es-Benz-37f</value>
      <webElementGuid>6d456a9a-f949-4d11-ae97-770e8692c206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53b2287a-e575-48eb-90da-6636a19d5ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senden']/parent::*</value>
      <webElementGuid>b44580c1-e045-4187-a494-83204cef19e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
