<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wb7-text_wb-text hydrated-37f-1fb-a67</name>
   <tag></tag>
   <elementGuidId>3817fe98-1e9b-4857-807e-a9d6bc1cdfe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>wb7-text.wb-text.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#required-dealerIddealer_locator wb7-text</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>wb7-text</value>
      <webElementGuid>b67f1e0d-3320-4a5c-b5cd-f3d8ba14d2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wb-text hydrated</value>
      <webElementGuid>6efd8998-b7e2-4cc6-9672-a41986974805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>555fab7d-a58c-453f-8684-96c056365d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2f87c69-8208-41dd-9b9a-d85b20216685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/wb7-text[@class=&quot;wb-text hydrated&quot;]</value>
      <webElementGuid>f69b169a-fefa-4b00-b477-393a6f340406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Mercedez/Page_Milestars I Mercedes-Benz/wb7-control-error_Dieses Feld ist ein Pflic_05e62f</value>
      <webElementGuid>943b1ccf-65b3-4a95-942d-af202eb7fe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1034494a-ff59-4987-a087-00950048da4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>f7874d89-3cb3-4777-982b-b6b4ff1dc077</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
