<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Show actions_sfxdash-1670340281212-492009</name>
   <tag></tag>
   <elementGuidId>de4fe67d-18fc-450e-8243-6164cd134aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@title = 'dashboard']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@title = 'dashboard'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;sfxdash-1670340281212-492009&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ac22a69c-8e78-446e-9d45-9a2b78f1e204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sfxdash-1670340281212-492009</value>
      <webElementGuid>21c6d48e-cfce-4216-bbd9-632ca30360f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>63f5ae16-d084-49ed-87c5-bd790c750460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.lightning.force.com/desktopDashboards/dashboardApp.app?dashboardId=newDashboard_1670340281211&amp;displayMode=edit&amp;networkId=000000000000000&amp;userId=0055D000004N9ctQAC</value>
      <webElementGuid>44704271-efdc-444a-947b-166d284843b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fe4fc0d1-f5b5-49c9-b6e8-204b0ba91b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;standalone dashboardTopLevelContainer desktopDashboardsDashboard&quot;]/div[@class=&quot;dashboardContainer&quot;]/iframe[1]</value>
      <webElementGuid>0dcd4c9a-aca4-4261-90cf-9c62c5b4f22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'sfxdash-1670340281212-492009' and @title = 'dashboard' and @src = 'https://katalon-inc--demo.sandbox.lightning.force.com/desktopDashboards/dashboardApp.app?dashboardId=newDashboard_1670340281211&amp;displayMode=edit&amp;networkId=000000000000000&amp;userId=0055D000004N9ctQAC']</value>
      <webElementGuid>e260ba17-e55d-4ba2-a6f8-e49e33ff1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='sfxdash-1670340281212-492009']</value>
      <webElementGuid>26b5b9c7-98a3-492c-b7e2-7c27739f89c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/div/div[2]/iframe</value>
      <webElementGuid>262d8c2f-a256-4aba-a765-272bba56078e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/iframe</value>
      <webElementGuid>23f3c9af-bb6e-42d6-92dd-d7149a4cf55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
