<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dashboardNameInput</name>
   <tag></tag>
   <elementGuidId>866f5fe1-ae7e-48db-bb5e-45cfb09ba111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class = 'slds-input' and @id = 'dashboardNameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dashboardNameInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb863d0c-b4f6-4f5f-b5eb-172199c90ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>bad39602-d1c7-45e3-a5df-852c9714d97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboardNameInput</value>
      <webElementGuid>46f99e26-067d-4a2d-a8cb-1b295289625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca9ffd86-037f-4a86-b4db-dd57ce8a7c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-name-error</value>
      <webElementGuid>ee0f6726-aa2f-4ee3-b69b-a2080c4670b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardNameInput&quot;)</value>
      <webElementGuid>b579218b-af61-4736-9224-084e6ca3747e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR_Salesforce New/Dashboard/Page_New Dashboard  Salesforce/iframe_Show actions_sfxdash-1670340281212-492009</value>
      <webElementGuid>c0d4bc69-e76b-4c4c-8f45-36beff802f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@class = 'slds-input' and @id = 'dashboardNameInput' and @type = 'text']</value>
      <webElementGuid>96b7511b-2382-4123-b8ae-d24026f906b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dashboardNameInput']</value>
      <webElementGuid>a0591e29-1f61-4e39-ac3c-35acdf1ef81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mT1sEPNKh-modal-content']/div/div/div/input</value>
      <webElementGuid>14817a27-5696-488b-ba11-e16e788c2b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ef9e445a-962d-4ce0-95bc-e1631defdafc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
