<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dashboardNameInput (1)</name>
   <tag></tag>
   <elementGuidId>050e67e5-8f2c-4064-bb5a-301f550cc487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class = 'slds-input' and @id = 'dashboardNameInput' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dashboardNameInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0bedee5-3680-4f7e-b864-6e03e0e4728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>738fcbb9-cf50-4d65-b1aa-d283bdc0e493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboardNameInput</value>
      <webElementGuid>943c1eae-2562-4433-8007-805f3c8547ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8afd7cd-2015-4de8-b7b2-d796b8d01217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-name-error</value>
      <webElementGuid>5940b22c-417d-4086-a814-771a6212b723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardNameInput&quot;)</value>
      <webElementGuid>4ffd464a-515b-426c-ab1d-773f3293f4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR_Salesforce New/Dashboard/Page_New Dashboard  Salesforce/iframe_Show actions_sfxdash-iframe2</value>
      <webElementGuid>101b1e8d-f254-4362-ac42-3346adba0a17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@class = 'slds-input' and @id = 'dashboardNameInput' and @type = 'text']</value>
      <webElementGuid>28c85d74-de47-46ee-aaa3-b930fa6f7185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dashboardNameInput']</value>
      <webElementGuid>6b3092a3-beb9-43f0-8f79-d0d086404d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1mvYX1rWj-modal-content']/div/div/div/input</value>
      <webElementGuid>5a3532c3-c795-405b-91d2-9a877977d692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aecefc8b-d48e-4e49-a669-404d3c584e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
