<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Number_vibki</name>
   <tag></tag>
   <elementGuidId>d0f7c15d-667e-4c77-99fb-db1a7be94f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchfield']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchfield</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;  &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d1b08ec-8eb2-41f3-9528-3a93398e97ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-forminput input js-searchfield-input searchfield-input upercase</value>
      <webElementGuid>092f64b5-7325-4c49-ae7c-830a4abb0e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vibki</value>
      <webElementGuid>e6979f85-a98b-42b2-ae5c-d1aa6e18f75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchfield</value>
      <webElementGuid>76405cd2-0d94-41b9-9352-28dd82acd60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field-nr</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>871a4565-9f24-433e-b364-db096d13fd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-t-name</name>
      <type>Main</type>
      <value>FormInput</value>
      <webElementGuid>3221c396-158e-450d-8806-8c0720338489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>39782c92-ef97-4204-93cc-f330dd6b0780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-t-id</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>e4050aa1-da0f-4440-81cb-ba70723b6d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchfield&quot;)</value>
      <webElementGuid>110761a3-bf25-450a-9e36-72a691cc1789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchfield']</value>
      <webElementGuid>b6e20f67-1bb5-435c-85dd-11d14d035a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='suggestLayer-85c34ac8-b27d-40aa-8e65-dd2dab8edf3b']/fieldset/div/div/input</value>
      <webElementGuid>76aac0b1-022d-44be-af24-1905a2234bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>0590312e-ef02-41ff-8bce-356c549f8fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vibki' and @id = 'searchfield']</value>
      <webElementGuid>bf638047-6718-4138-a1f8-1569b21ca5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
