<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verify</name>
   <tag></tag>
   <elementGuidId>f151ea31-b7ff-40f9-8c3d-0a753d81c9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::div[23]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button-submit.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Verify Answers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1255c11d-aa96-41c1-b251-7be17279edbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-submit button</value>
      <webElementGuid>81f5b50d-3b48-4be8-95f4-21a6565d5a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>14025025-3942-40e6-904f-40692d33f3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>976c93bf-627a-4775-9394-6202bb56f4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Verify Answers</value>
      <webElementGuid>64c6660a-fdb9-4e2d-a13d-8582c8ade37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Verify Answers</value>
      <webElementGuid>332e4870-596c-45b2-9267-03a0fbdf524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>e517c259-6902-4b2e-836f-fedfef4fdc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no-selection&quot;]/div[@class=&quot;interface-wrapper&quot;]/div[@class=&quot;interface-challenge&quot;]/div[@class=&quot;button-submit button&quot;]</value>
      <webElementGuid>9efe4176-1be7-41e2-b941-f660098e5902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Myfancyfeast/Page_Challenge  My Fancy Feast/iframe_1</value>
      <webElementGuid>3e832394-c9b5-4890-bb58-a8ec3252b938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::div[23]</value>
      <webElementGuid>7ac489fa-7176-4a6c-8822-96ea8bb28227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>3c426182-8b02-443b-9c81-fff399c2bc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
