<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department_Department__c</name>
   <tag></tag>
   <elementGuidId>619f9da2-0783-4712-ace1-ea6951653c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-237</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a43165cc-733c-447d-b55a-2994e389d0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>00c971c1-2fee-44f9-ac8d-ccb4046cd934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a317286-01f1-41e2-8717-36111a97f5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-237</value>
      <webElementGuid>455ec347-e862-433c-8bcd-0f610cc41546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>4999b534-efd9-490a-95d4-556cf7df6484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Department__c</value>
      <webElementGuid>ab48dda4-a0f0-4c3b-8d0b-b2ee11424433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-237&quot;)</value>
      <webElementGuid>ce4dec09-6405-4f27-937f-7739f0634399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-237' and @name = 'Department__c']</value>
      <webElementGuid>fb13ee62-85ee-4f30-a715-cbc4d01c4e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-159']/div/slot/records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>151f374d-42ad-4bb0-b40b-a89affdde488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-237']</value>
      <webElementGuid>c946837a-dfdb-4acd-81ca-13c9e38cad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>5f933102-ee25-45c2-8ca6-db58fa9a4801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
