<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_default_demo-example-sc-grlnui-1 cddDli</name>
   <tag></tag>
   <elementGuidId>628274b6-5d1c-489d-9577-befc8c776840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/main/div/div[2]/article/div[3]/div/div[2]/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-example-sc-grlnui-1.cddDli</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gatsby-focus-wrapper iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9041565e-c342-41a5-8420-b853eecc3acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-error</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91e34adf-d45f-4a70-bf44-1dfe347d7e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-example-sc-grlnui-1 cddDli</value>
      <webElementGuid>e3b6c80e-642e-4529-81ff-20200637ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7dc49510-410d-4ddb-abfc-2cc71c851e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>99e83df8-44bd-4c0a-9282-b3b4e1362161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/kendo-angular-ui/components/dateinputs/examples/calendar/basic_usage?theme=default-ocean-blue&amp;themeVersion=8.2.1&amp;env=undefined</value>
      <webElementGuid>01b946b2-3f77-45fc-804a-7104291e9525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/main[@class=&quot;container-sc-n150ym-0 gHslwQ&quot;]/div[@class=&quot;row-sc-4zdjyf-0 dBtUqS&quot;]/div[@class=&quot;column-sc-1t518bt-0 bQJVbx&quot;]/article[1]/div[3]/div[@class=&quot;demo-sc-1m0h1qa-3 idmYCz&quot;]/div[@class=&quot;tab-panel-sc-i9ulc3-0 WAjlJ&quot;]/div[@class=&quot;box-sc-1g51uh7-0 gftFPB&quot;]/iframe[@class=&quot;demo-example-sc-grlnui-1 cddDli&quot;]</value>
      <webElementGuid>fb0e7b08-09a4-4833-b778-d31a03e67d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/main/div/div[2]/article/div[3]/div/div[2]/div/iframe</value>
      <webElementGuid>59ad983e-0687-4a45-9b5e-58d33c1d4375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ca232f1d-7749-4026-bce0-6cf07bfb527b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
