<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_StackBlitz</name>
   <tag></tag>
   <elementGuidId>b66a9c7d-d211-418b-86b4-4a59ee269d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'StackBlitz' or . = 'StackBlitz')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#open_in_stackblitz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#open_in_stackblitz</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>07c1d610-f4c1-4cbf-bbe0-9f8251d9a484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>open_in_stackblitz</value>
      <webElementGuid>bf6ffe6e-37e5-4a6a-acbb-50d6ecef1319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>open_in_codesandbox</value>
      <webElementGuid>3cfdc824-c7b9-4265-9be9-fd8f206b9274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-menu__EditOptionItem-sc-vblcaq-5 bkSduI</value>
      <webElementGuid>8c4f88e7-603c-4f98-9627-06ddfab8eafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>StackBlitz</value>
      <webElementGuid>1403d7f2-c749-4763-934c-5c55928bd45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open_in_stackblitz&quot;)</value>
      <webElementGuid>0070b0a3-280d-4848-afbe-835410dedf9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'StackBlitz' or . = 'StackBlitz')]</value>
      <webElementGuid>018f0dbb-fd43-4035-b5d2-3380c7588f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='open-in-list']/li[2]</value>
      <webElementGuid>574d2bb6-87ce-4ba7-be2d-5fb1250cd7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='open_in_stackblitz']</value>
      <webElementGuid>adfc2db1-88f4-4c9d-96a1-a1b9a98462c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CodeSandBox'])[1]/following::li[1]</value>
      <webElementGuid>3dd0e7d1-491c-45da-81f0-01401056c792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPEN IN'])[1]/following::li[2]</value>
      <webElementGuid>a9d0ee39-79fb-44a0-a503-9f083c49bd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Window'])[1]/preceding::li[1]</value>
      <webElementGuid>66644af6-6dfb-401c-90ea-f522fd366623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/ul/li[2]</value>
      <webElementGuid>d59bc19b-d345-4e2e-81bf-3bead8a71f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
