<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cat_involvement</name>
   <tag></tag>
   <elementGuidId>61cf03d7-4216-4e3a-9406-55c471b04ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-involvement-breeding-cattery</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-cat-involvement']/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Breeding Cattery\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5895a4c-ba52-4a53-947a-92dab7b6d9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-involvement-breeding-cattery</value>
      <webElementGuid>d6abf533-c7df-4d05-b3a2-62accbf4e3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>60ea02eb-f7a3-45d9-a526-c02baecc16fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-involvement-breeding-cattery</value>
      <webElementGuid>6090c3f5-1fa9-4784-80bf-46c8544e0bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_involvement</value>
      <webElementGuid>03211682-2791-4c01-9299-1ec271f54503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Breeding Cattery</value>
      <webElementGuid>bbced30c-91eb-45a0-b1df-dc420f52a5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-radio form-radios</value>
      <webElementGuid>52df8126-1fd3-48ec-9a24-b926be56ca4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>6fe9561f-ef55-4042-9317-51aa6afa3278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>944234cf-bb1f-4672-9107-5bf12148818a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-involvement-breeding-cattery&quot;)</value>
      <webElementGuid>bd258857-1569-481b-85e0-b8e60a9eb05f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-cat-involvement']/div/input</value>
      <webElementGuid>5a8e4e48-14ed-432d-aa20-bd2433c2f208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-cat-involvement-breeding-cattery']</value>
      <webElementGuid>0261ed17-1567-4ff3-b295-e968fc541a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>3a72bff2-3573-4a7d-8928-6b2cf1150655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
