<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cat_breeditems0cat_primary_number_of_c2b1c3</name>
   <tag></tag>
   <elementGuidId>89ae612f-9d81-4f97-b4f8-22b90187e1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[5]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;# of Kittens Produced Annually\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cecef9c-1142-4a4e-bbd9-0d4b66f7b159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      <webElementGuid>8fbae610-78a1-424c-b5bc-aa1a211ae5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b8bf5e8e-fb4e-49ff-a3e1-ad83d8ee396f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      <webElementGuid>57de527e-b0bd-4f47-86af-536bf36eeae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_breed[items][0][cat_primary_number_of_kittens]</value>
      <webElementGuid>f7690a3f-8504-400c-b00c-a3cb07c61912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f33d82b9-b152-4423-9f98-679abf047057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7d4f3b1-8036-49fe-adbd-11f59abcd182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>0558a7c9-afaa-442b-86c8-7ebab1d9883f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2567ca50-7cc6-4108-a45c-18b6404c6aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>4959eb01-cb9f-4937-b091-9c063e088894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f728d927-9f3e-4b5f-9b11-e3157ce479e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f973da02-5e19-45b9-b5ce-59aaa0d1e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>ef8add62-dde1-46bc-89aa-d23b13a94709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-breed-items-0-cat-primary-number-of-kittens&quot;)</value>
      <webElementGuid>3ff8cd9d-c5df-400a-804c-e7f352a64a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[5]/div/input</value>
      <webElementGuid>f9da5600-2a54-4af1-85e9-492391be9711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-cat-breed-items-0-cat-primary-number-of-kittens']</value>
      <webElementGuid>7aadfb20-e6c5-4766-ad94-e4d780d5ca08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>f5cb2d8c-2139-48ed-a7d1-fd4448a0035f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
