<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cat_breeditems0cat_primary_number_of_e5e8f4</name>
   <tag></tag>
   <elementGuidId>109aea4f-e175-4833-8f64-2006cf8e0fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-breed-items-0-cat-primary-number-of-breeding-females</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[4]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;# of Breeding Females\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>582b4b6d-ca9a-4a8f-8784-3a5720822310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-breeding-females</value>
      <webElementGuid>50a6a20e-cf67-46ae-93d8-c4d214a21d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>935d6453-fde7-4eb5-ba4e-b17bd3655e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-breeding-females</value>
      <webElementGuid>a6f8b256-eb07-4836-8f35-0dd30b75dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_breed[items][0][cat_primary_number_of_breeding_females]</value>
      <webElementGuid>e16fcb8e-0471-4984-b535-30d00582045c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c7d5a455-6d5a-47db-990a-6c48e08de957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd2ee17e-58d6-4154-9ed6-a3c52deed186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>c9b1c99b-56f2-4308-b2ab-d6fd824c1830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f6dd5bd3-af76-49f0-9aa2-a6fbc8e83c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>a103a29e-a524-4cc6-84b5-1cd47cec5e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f4edfb20-e68f-4634-8706-e05aef9a7baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ceaf953-60bd-40e3-90bd-804f504cf0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>e9d4c1bf-9f3a-4af0-a622-e04c4d157bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-breed-items-0-cat-primary-number-of-breeding-females&quot;)</value>
      <webElementGuid>bdfab770-580a-4f7c-8f5f-4dce3c551c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[4]/div/input</value>
      <webElementGuid>b9b925de-b37d-4ead-85ed-922389b62d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-cat-breed-items-0-cat-primary-number-of-breeding-females']</value>
      <webElementGuid>a0206468-2061-4b58-9a97-d7fc847c1683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>9b2b7d9d-434e-44b4-aab0-674225abd3f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
