<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__primary_phone</name>
   <tag></tag>
   <elementGuidId>2f73b646-1eb2-4af2-8cdc-ac6b678887f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-primary-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-part-one']/div[9]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Primary Phone Number\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>984fc49e-a0e1-4328-9349-650487de30b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(^\d{10})</value>
      <webElementGuid>a86fd240-1ff6-457d-9d9d-1586a0a9ff2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-pattern-error</name>
      <type>Main</type>
      <value>Primary Phone Number needs to have 10 digits without hyphens.</value>
      <webElementGuid>1cb99299-14c6-4ef7-933b-fb84c69dd027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-primary-phone</value>
      <webElementGuid>14be8fa2-0345-4e7b-adf7-28babdb9e2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2d1455f9-14e1-42f2-aaa3-461431da9551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-primary-phone</value>
      <webElementGuid>9bd5b5e4-663b-4391-83a9-b886b9c3df2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primary_phone</value>
      <webElementGuid>0b4d67ce-011e-4503-8221-6d6d105f3b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ef0fc0b1-5ae2-490e-bd48-53342632cf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>f97451c9-99fe-44af-a7a3-a43b3a60228c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10-Digits, No Hyphens</value>
      <webElementGuid>3251f403-68f4-4c53-a7f6-34d17a03228a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-tel required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>a7ef5118-edac-482c-bee4-9d0575394c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7fdbd5bf-e7b4-4537-b47f-adef10247725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9a5eb72-1288-4c25-aff1-bd5f516d1ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit webform-required-error</value>
      <webElementGuid>838e3818-1e7c-4202-b5e8-acc34117063e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-primary-phone&quot;)</value>
      <webElementGuid>da7552bd-ca00-4705-8635-79d500b03d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-part-one']/div[9]/input</value>
      <webElementGuid>232bea6a-8fa8-4c72-a2f2-b1a3e5513305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-primary-phone']</value>
      <webElementGuid>92e3c1f6-1867-4a6a-a3ac-6f6b4c7f3231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>1b0176be-1549-42de-94a5-c1cac345aa93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
