<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -Purina Representative (ple_29890f</name>
   <tag></tag>
   <elementGuidId>23985d58-a96d-4a29-a132-7936318e7722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-learn-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-final']/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How did you learn about Pro Club?\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e1ff6c8e-13b4-4571-a81f-3c030bec6d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-learn-method</value>
      <webElementGuid>e0646085-6a84-4fd1-af2c-93ce3c9a0ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-learn-method</value>
      <webElementGuid>2fecced0-143c-416c-bb6e-fc78797e15b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>learn_method</value>
      <webElementGuid>8cd993a3-ad5d-4f2b-be12-4bb34f877e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>1dbd8b2d-4468-43d8-9377-2503d82b1bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5ddb5337-d92a-4066-90f3-4c1747ce81c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4be495a5-8482-4390-a586-887405940324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -Purina Representative (please provide name.)Purina-sponsored eventReferred by another Pro Club MemberMagazine AdAKC Website/EmailBreed ClubHandlerJudgeKennelToday's BreederTrainerVetBreederEnthusiastSocial Media (Facebook, Instagram, Twitter etc)Internet Search</value>
      <webElementGuid>1a639749-acc8-4d5a-a94c-6cf49d9ae74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-learn-method&quot;)</value>
      <webElementGuid>f9a833ba-c08c-4b40-a4ac-f5f5d35db915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-final']/div/select</value>
      <webElementGuid>e3cffbfa-0cfe-4876-8091-7391f5c78059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-learn-method']</value>
      <webElementGuid>226ffd84-033d-4eca-9c29-e0c9d7f23e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>bae889dd-abe4-4c5c-80c4-9764daa665a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>8102813f-1404-4d8f-a92c-ae779652da9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cc605778-a6f2-4552-84c4-287e8a158006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
