<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -AbyssinianAmerican Bobtail_defdb8</name>
   <tag></tag>
   <elementGuidId>3ed26afa-b4a0-4b13-9122-bd8d09549dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-breed-items-0-cat-primary-breed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;What primary breed of CATS do you care for?\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>916eef47-0f3c-4679-9a0f-a41977b7f1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-breed</value>
      <webElementGuid>52133b20-240c-4051-a820-e127e769b8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-breed</value>
      <webElementGuid>0cd83915-64e3-4c9e-ac41-915d48ec8463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_breed[items][0][cat_primary_breed]</value>
      <webElementGuid>1ca2eb55-03df-485e-bf5a-98ae2a2fd9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>342121ab-309c-414b-9dfc-93bd4286cb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>07d0357e-5541-4a33-9bc0-09a4b743c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e193204c-724a-40a3-a5fe-14802326a5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -AbyssinianAmerican BobtailAmerican CurlAmerican DomesticAmerican ShorthairAmerican WirehairAnatolianAngoraBalineseBengalBirmanBombayBritish ShorthairBurmeseBurmillaCalicoChartreuxChinese Li HuaColorpoint ShorthairCornish RexCymricDevon RexDomestic LonghairDomestic ShorthairEgyptian MauEuropean BurmeseExotic ShorthairHavava BrownHimalayanJapanese BostailJavaneseKashmirKoratLapermMaine CoonMalayanManxMisc.MunchkinNorwegian Forest CatOricatOriental LonghairOriental ShorthairPersianPixiebobRagamuffinRagdollRussian BlueScottish FoldSelkirkrexShorthair MiscSiameseSiberianSingapuraSnowshoeSomaliSphynxTiffanyTonkineseTurkish AngoraTurkish VanOther: Breed Not Listed</value>
      <webElementGuid>e0fb4677-7ddf-432e-854e-c862f3facd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-breed-items-0-cat-primary-breed&quot;)</value>
      <webElementGuid>5cefa05d-dd5b-40bc-95b1-32a58a7463c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[2]/div/select</value>
      <webElementGuid>257e2e5e-d1e2-40d0-9fbd-0c205b5a56d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-cat-breed-items-0-cat-primary-breed']</value>
      <webElementGuid>c8c44722-1711-449a-9fee-5c90a61b4778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>8195bdf9-93a3-4a49-929c-405c7f68d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/preceding::select[1]</value>
      <webElementGuid>f742bfc7-852c-49da-819f-eff4a273bcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>59940679-f6ae-4c20-a63c-5ad7b48ab9cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
