<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -I have a cattery.Does Not Apply</name>
   <tag></tag>
   <elementGuidId>b031e4bf-9ae6-443d-bd6d-c913cf3ad780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cattery-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-part-one']/div[5]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cattery Info\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9d5aa84-6b1d-4d42-917c-245b827f157a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cattery-info</value>
      <webElementGuid>209e7dc5-629a-4d43-a153-321cfb579b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cattery-info</value>
      <webElementGuid>f62e216c-43c4-4b4d-9194-3569be428f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cattery_info</value>
      <webElementGuid>58e70e13-e578-46ec-a40e-087c2c52dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>9587d08c-7f28-48fe-ad7e-687b7c5d8897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-states</name>
      <type>Main</type>
      <value>{&quot;visible&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;cat&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}],&quot;required&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;cat&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}]}</value>
      <webElementGuid>6a5d889e-dc73-40d4-9b54-1692f0e61fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>c8f057a0-788f-4001-a55a-70d3327d519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7bd27118-46cd-40a0-9567-cd5738ee675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb405129-f50d-4830-931a-e9b81f347724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -I have a cattery.Does Not Apply</value>
      <webElementGuid>9acdaa95-bcb3-4a4d-870f-8dc22cea2192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cattery-info&quot;)</value>
      <webElementGuid>7f8fd5a2-9e49-49c3-b873-73fd13cb0528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-part-one']/div[5]/select</value>
      <webElementGuid>d9b9bac0-9215-493d-be73-e6ac8b783cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-cattery-info']</value>
      <webElementGuid>64232bc0-bc86-4126-9d54-326d7a33ed62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>b13cab44-8485-46f3-868b-bff3b90e50c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>62af33f4-f22d-45dc-9ff5-9108d07e773f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>864e3320-b586-4ded-9309-c6d74a1741fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
