<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8ec0813f-ed7a-44fc-b91c-635d58e5229d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/records-highlights-icon/force-record-avatar/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.record-avatar-container.slds-avatar.slds-avatar_small.icon.slds-m-right_small > img[title=&quot;Lead&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d101f3bf-c314-4071-9bcc-2624d304f493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/lead_120.png</value>
      <webElementGuid>27e7a77b-f0d1-4d81-8772-fcc1ac62835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lead</value>
      <webElementGuid>e24f5648-c716-4255-8518-4c51c7b173f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestionsList-646&quot;)/search_dialog-instant-result-item[2]/div[@class=&quot;slds-text-link--reset slds-grid slds-grid--vertical-align-center slds-truncate instant-result-item slds-p-left_small two-fields instant-result-item-record-suggestion focused&quot;]/div[@class=&quot;slds-icon_container iconContainer instant-result-item__icon&quot;]/records-highlights-icon[1]/force-record-avatar[1]/span[@class=&quot;record-avatar-container slds-avatar slds-avatar_small icon slds-m-right_small&quot;]/img[1]</value>
      <webElementGuid>c3e513e5-7509-49d7-9d42-729c11ec3df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suggestionsList-646']/search_dialog-instant-result-item[2]/div/div/records-highlights-icon/force-record-avatar/span/img</value>
      <webElementGuid>893a0742-f9d0-49be-a0c1-c9370987019c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Lead'])[2]</value>
      <webElementGuid>ebfd9219-d0a0-4034-8ccb-fda2b92be76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/records-highlights-icon/force-record-avatar/span/img</value>
      <webElementGuid>8307f6cf-252e-46cf-a7a0-c546538f158a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/lead_120.png' and @title = 'Lead']</value>
      <webElementGuid>cc093ec5-466f-41b9-b91b-c4f0698262d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
