<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Compute</name>
   <tag></tag>
   <elementGuidId>9e6c5963-1c52-4419-ab63-6b918f905f6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-teal</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Compute' or . = 'Compute')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mlc-vehicle-qqt']/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Compute&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38f643f0-c33d-489c-aea3-76189c59545d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9283472f-887f-484f-b1e9-ce2a2d6b4c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-teal</value>
      <webElementGuid>bc8ca23b-1715-494b-9deb-d1210f779936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compute</value>
      <webElementGuid>33f0daa1-812f-45db-aae3-de5e49a209b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mlc-vehicle-qqt&quot;)/div[@class=&quot;cmp-CustomContainer__inner&quot;]/div[@class=&quot;aem-container aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;aem-GridColumn aem-GridColumn--default--2 aem-GridColumn--offset--default--5 aem-GridColumn--default--none&quot;]/div[@class=&quot;cmp-custom-form-cta-button align-items__center justify-content__center&quot;]/button[@class=&quot;btn btn-teal&quot;]</value>
      <webElementGuid>490b74eb-fcef-4499-ac08-9197f15c073f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mlc-vehicle-qqt']/div/div/div[2]/div/button</value>
      <webElementGuid>12d24fa5-ea72-439d-a69d-1152bcaafd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>09765232-daa7-47ae-99a3-032d342d1936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*mandatory fields'])[1]/following::button[1]</value>
      <webElementGuid>1f9451e2-a97c-4285-8309-b92656044cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[1]</value>
      <webElementGuid>840aefc6-bd08-4e57-89d5-120abbce66e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='comprehensive coverage'])[1]/preceding::button[1]</value>
      <webElementGuid>70064d8e-93ad-44f7-8f15-d969588bc5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exclusive roadside services.​'])[1]/preceding::button[1]</value>
      <webElementGuid>6ba809fe-19d9-4f19-b9c5-b43046e4e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compute']/parent::*</value>
      <webElementGuid>83a3929e-954f-4ae3-9d53-a89609378242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>9fe20f52-8fba-4111-9f13-f3ccae439213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
