<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_roadAssistance</name>
   <tag></tag>
   <elementGuidId>f13343f6-2a97-439a-9b5e-abdb7b73b24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#roadAssistance-false</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;roadAssistance-false&quot;)[count(. | //input[@data-label = 'No']) = count(//input[@data-label = 'No'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mlc-vehicle-qqt']/div/div/div/div/div/div[5]/div[2]/div/div/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#roadAssistance-false</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c88b1c9a-3da8-4772-9174-541d0dba9d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e97d5eac-709b-477e-9ad1-05aecdfa557d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roadAssistance-false</value>
      <webElementGuid>c54a64ea-cae9-46cc-9469-8d08d363ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roadAssistance</value>
      <webElementGuid>fda45363-bc2e-4412-90b7-02a4b32c7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>fc9e08da-8565-4d11-90b6-609aa49f5ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roadAssistance-false&quot;)</value>
      <webElementGuid>a55a777d-c1c9-4fd5-85bf-523f1d300c7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mlc-vehicle-qqt']/div/div/div/div/div/div[5]/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>9a307a4b-8cf3-42ff-bc92-eb40ccc59285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='roadAssistance-false']</value>
      <webElementGuid>f056212b-fa85-483a-83a6-612b4c164494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>46e29fac-3a69-4ea7-8a92-b564fff4597a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
