<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__actOfNature</name>
   <tag></tag>
   <elementGuidId>18c4c911-d800-4d28-b258-b9b404234e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actOfNature-true</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;actOfNature-true&quot;)[count(. | //input[@data-label = 'Yes']) = count(//input[@data-label = 'Yes'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mlc-vehicle-qqt']/div/div/div/div/div/div[5]/div/div/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#actOfNature-true</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01e5173b-fa96-4055-851b-ba83898381e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>10aca1ec-8632-4d5b-81f6-73144561cee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actOfNature-true</value>
      <webElementGuid>14a820f2-eb3f-4e3f-b999-170c4a427db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actOfNature</value>
      <webElementGuid>1f478441-bfd5-42b6-9d3b-1745e35db653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>231832c9-8221-4d00-b04b-8a88ae6052e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actOfNature-true&quot;)</value>
      <webElementGuid>96498410-f0a3-4067-89e1-c3aaf2c23fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mlc-vehicle-qqt']/div/div/div/div/div/div[5]/div/div/div/div[2]/div/input</value>
      <webElementGuid>4d6335b5-bd60-4be5-87f8-d86b08042190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actOfNature-true']</value>
      <webElementGuid>641712c5-5fbc-4cef-b57e-85badeb29884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/input</value>
      <webElementGuid>1addf770-62b1-4463-9bbb-eb1980e6d121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
