<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_breeditems0dog_primary_number_of_f1f29a</name>
   <tag></tag>
   <elementGuidId>a1c753a5-b802-4e7a-b607-786eb1f17547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-breed-items-0-dog-primary-number-of-breeding-females--l5RjeDDrJrg</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-breed-items-0-dog-primary-number-of-breeding-females']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Change order What primary breed of DOGS do you care for? * # of Adults * # of Breeding Females * # of Puppies Produced Annually * Add new item after item 1 Remove item 1&quot;i] >> internal:label=&quot;# of Breeding Females\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8f56813-5d83-4cc4-8875-ccfd518953e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-number-of-breeding-females</value>
      <webElementGuid>c0974b54-5d8e-4f5b-8fcb-6c57ac647b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>37c7186f-bc28-469c-a6a4-2fea47401aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-number-of-breeding-females--l5RjeDDrJrg</value>
      <webElementGuid>c0ea5604-4b0d-400e-a498-3acbe7e8b1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breed[items][0][dog_primary_number_of_breeding_females]</value>
      <webElementGuid>56fc5c5c-ca9b-4fb0-b923-96ba2d0dd92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>47b24b03-d05d-45a0-aaf9-9417c42b665c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9bad8bae-164c-4388-a771-c7e616736a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>cf7ea774-70ed-4c04-a044-302ad7086f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>aa587149-91bc-48cc-b23f-9427412bbe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>069ea635-a28d-4728-953d-f12d2ed6dfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cea24019-b700-4c03-ae79-a26e3423a1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>373798a2-6583-4411-bc68-750059b1e1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>9b808d4e-1260-4f15-8fc7-ae9ee7852005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-breed-items-0-dog-primary-number-of-breeding-females--l5RjeDDrJrg&quot;)</value>
      <webElementGuid>c125c0b4-cb4e-49ad-bbef-697790aeed81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-dog-breed-items--Mfiv3skfHaM']/tbody/tr/td[4]/div/input</value>
      <webElementGuid>78393c06-1f6f-44b1-8db1-5ee40a4235f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-breed-items-0-dog-primary-number-of-breeding-females--l5RjeDDrJrg']</value>
      <webElementGuid>7cf8acf1-07f7-43e0-8487-2057ee7391af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>646fc6ea-5fe0-4e1c-8605-c36cb799f7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
