<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_primary_breed_clubitems0_item_</name>
   <tag></tag>
   <elementGuidId>1443471b-ded4-4c63-8e90-d618100332be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-primary-breed-club-items-0-item-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-dog-primary-breed-club-items']/tbody/tr/td[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Breed Club and/or conservation organization&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4c12536-afd3-44f2-a246-19e003975d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-primary-breed-club-items-0-item-</value>
      <webElementGuid>3557ae71-dd99-42b5-a209-e92156793d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed2d80e9-52cb-4593-b6d9-6bc878c93f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-primary-breed-club-items-0-item-</value>
      <webElementGuid>42465887-19e9-47aa-bfe3-14d4f1495034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_primary_breed_club[items][0][_item_]</value>
      <webElementGuid>e0a33d18-aef6-427a-8e0a-01a1451595a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>8bf49c37-21f5-436d-89ad-3d6eed7f391c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>afbcfcc4-dab5-4d7a-80b3-518257d1591f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Breed Club and/or conservation organization</value>
      <webElementGuid>bdb40a07-e3da-4094-9eaf-99c5d01d3b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>ded69e04-70ea-424f-88da-4744f57fd206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>e7f85e85-3bcd-46e0-ae4a-92e0bec85cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-primary-breed-club-items-0-item-&quot;)</value>
      <webElementGuid>ab9bce86-0e56-4539-95bb-b6a72feece91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-dog-primary-breed-club-items']/tbody/tr/td[2]/div/input</value>
      <webElementGuid>8cf020c0-3c22-41a2-9cb0-8fbc4cc60b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-primary-breed-club-items-0-item-']</value>
      <webElementGuid>d9ee79c4-3b75-455c-b8f4-9d96b27cc304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>6c3e6601-586a-4fe3-b817-22e5aa1d5d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
