<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__primary_phone</name>
   <tag></tag>
   <elementGuidId>71e527c1-64fe-41a8-95da-988f2887258a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-primary-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-part-one']/div[9]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Primary Phone Number\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>676a3895-fd98-4118-b19f-1fab724494ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(^\d{10})</value>
      <webElementGuid>a35c02ec-d6fe-4b70-adb5-3a4b8e563619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-pattern-error</name>
      <type>Main</type>
      <value>Primary Phone Number needs to have 10 digits without hyphens.</value>
      <webElementGuid>01d1d4ba-1359-4a5b-a6bc-4fc7d01f7896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-primary-phone</value>
      <webElementGuid>b0f1cf9f-c329-42f0-9433-6d40a4fd0fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>16aa8664-bea3-4d2f-b407-e2de5de32548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-primary-phone</value>
      <webElementGuid>0895fa80-c908-4c0e-8f7e-a96ddf8f6ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primary_phone</value>
      <webElementGuid>471e2e57-2b37-4fb5-85b0-334c3bcd4d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8c11df94-3929-40f2-9902-35335dadbc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>f0636b82-74b3-48ae-9ae1-86bbeb51ec94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10-Digits, No Hyphens</value>
      <webElementGuid>45dc39c7-7e86-4e75-b9e1-4c99d3cd4e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-tel required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>074e12a1-daa1-4e60-a129-8eb6d09d7e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5efea169-0bb0-461d-93c1-ce9884616316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e58af1f2-fb99-4ddf-93f0-4851eb59200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit webform-required-error</value>
      <webElementGuid>c696bff7-6f5e-4f7d-a239-7bebc9402526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-primary-phone&quot;)</value>
      <webElementGuid>285a4522-d60b-4f7d-9b63-fdfe0dde156f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-part-one']/div[9]/input</value>
      <webElementGuid>f859f630-010b-4ff3-9896-d2ca035c301b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-primary-phone']</value>
      <webElementGuid>72e5f624-440b-4c8d-a1b0-24db8dd0e4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>904d1ea7-4b5c-4ff4-a107-5d7224ede2fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
