<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree to receive email and other ma_214654</name>
   <tag></tag>
   <elementGuidId>f677f028-1a1c-4fb7-861f-653d7fe23442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-accept-terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-final']/div[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-accept-terms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ca512a-9d04-41b6-87b1-e6ae50ec914d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-accept-terms</value>
      <webElementGuid>259bf1ef-8736-4d6e-8e75-6a01a619dbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>edit-accept-terms--description</value>
      <webElementGuid>e9e2432c-d3ae-40d7-82c8-e151bac100be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fdd7c778-bd35-4d02-8e72-1067b3aeead7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-accept-terms</value>
      <webElementGuid>a4606e26-50a5-4ada-bf01-54ea8aac8a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept_terms</value>
      <webElementGuid>d4c5453b-1578-4a8e-a907-ab9e986b060c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fd607186-042c-45cf-8245-dcca96fe5cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox required</value>
      <webElementGuid>52c3746b-45e2-484e-abd9-ad1c03bf0846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3e42bcc0-944c-435c-a374-8832fc0f5f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f694c27e-fae6-43d5-a97c-98e694063fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>caf99a75-1a02-4953-a63b-7027953b78fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-accept-terms&quot;)</value>
      <webElementGuid>a816a46b-106a-4e0b-a599-f1618d6db2f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-final']/div[5]/input</value>
      <webElementGuid>d0bf0a71-e257-4c6b-bd6a-1cf76da0c0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-accept-terms']</value>
      <webElementGuid>528779b6-8981-49da-9625-48d993bc61b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>205fa39f-6b58-4577-a702-49090c313f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
