<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cat_breeditems0cat_primary_number_of_adults</name>
   <tag></tag>
   <elementGuidId>93c4a4b3-fdf5-4323-b113-4966eb952e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-breed-items-0-cat-primary-number-of-adults</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-cat-breed-items-0-cat-primary-number-of-adults']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;# of Adults\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9aa7c28-ee16-412a-a388-c9f5bab2b10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-adults</value>
      <webElementGuid>9cfb3ba2-0bf6-4f5a-9009-3058dacd9ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d096f6f9-17d6-45ff-9bcf-ad75faad5406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-adults</value>
      <webElementGuid>a0411f3a-eb30-4c15-afef-76cd14c33855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_breed[items][0][cat_primary_number_of_adults]</value>
      <webElementGuid>4e852d89-fcb3-4fa1-9cfb-f85c308c09e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e6d6da86-4713-48ab-9b69-d1f619cec991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee422c5f-bedf-44de-8f45-f2be52b7d8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>9b939f58-38c1-489d-96de-107701b6bbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d1f0e602-6bef-4036-a5d7-92695b26748a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>ce92fc83-d6d9-41ac-8d67-1c7e24ed78c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e312f63c-e731-4306-80d2-68c0bdfb431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92fe5d2b-2a62-4bfb-a07d-af040777aa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>02db3618-8e95-4445-b812-9e2c7b124095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-breed-items-0-cat-primary-number-of-adults&quot;)</value>
      <webElementGuid>dbccbce4-dfc6-472b-9572-5aa4aea04be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[3]/div/input</value>
      <webElementGuid>d67f1735-197d-4eea-9267-f468826145ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-cat-breed-items-0-cat-primary-number-of-adults']</value>
      <webElementGuid>12da0aaf-67fb-43d0-8393-170edc4f2ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>56c6c41b-d9ba-4040-bd5a-e8a1da6196c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
