<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_breeditems1dog_primary_number_of_1dafa8</name>
   <tag></tag>
   <elementGuidId>0ffc8775-4272-4415-a7ea-1917a27e37b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-breed-items-1-dog-primary-number-of-puppies--o53DGt_Oxz0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-breed-items-1-dog-primary-number-of-puppies']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-dog-breed-items--Mfiv3skfHaM']/tbody/tr[2]/td[5]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Change order What primary breed of DOGS do you care for? * # of Adults * # of Breeding Females * # of Puppies Produced Annually * Add new item after item 2 Remove item 2&quot;i] >> internal:label=&quot;# of Puppies Produced Annually\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab5a9224-f730-40b6-9e4f-2f40b31994d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breed-items-1-dog-primary-number-of-puppies</value>
      <webElementGuid>7fb9c849-4892-44e7-a578-4f5016f2996c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>923b004f-e663-449b-86f4-8979b7785f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breed-items-1-dog-primary-number-of-puppies--o53DGt_Oxz0</value>
      <webElementGuid>a54cd258-a375-44c9-a242-abc412b68e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breed[items][1][dog_primary_number_of_puppies]</value>
      <webElementGuid>72070d28-e5ba-432a-b8dc-9536fec35adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ca2d95db-b360-4c34-ac0e-22743c7f3c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>260d2d8a-0266-4691-b7f6-7e3be4a08fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>951e06b4-b88c-417f-a4f0-1aeaad9adad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cf767a18-5465-40f3-bf8b-f713fcd37bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>21802f89-0ebc-48ec-9362-2c6863d3a553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>516ac64b-062b-43e3-a474-7e72a739a439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a80a626c-a96d-4c48-b149-910598618cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>3cedb52f-b546-4c38-9868-c6f95be33142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-breed-items-1-dog-primary-number-of-puppies--o53DGt_Oxz0&quot;)</value>
      <webElementGuid>872d5699-738b-481e-b369-5f01ded37b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-dog-breed-items--Mfiv3skfHaM']/tbody/tr[2]/td[5]/div/input</value>
      <webElementGuid>ce32d2c4-7300-4579-a275-b6e77b25d67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-breed-items-1-dog-primary-number-of-puppies--o53DGt_Oxz0']</value>
      <webElementGuid>da808d6d-1c3b-45dc-8a1f-3537d9783e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/input</value>
      <webElementGuid>c7f18bf6-2658-490e-8fa9-e162a2beed54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
