<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dog_breed_table_add</name>
   <tag></tag>
   <elementGuidId>47e3fa7b-a87d-43f0-ab27-0c0b6b3897db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-breed-add-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05bc5cc7-3cab-4c3e-8dd7-a225d2107c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breed-add-submit</value>
      <webElementGuid>efbf8223-44c3-4614-85fd-f1f6c0531ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formnovalidate</name>
      <type>Main</type>
      <value>formnovalidate</value>
      <webElementGuid>2abaefc0-ad57-4518-afe2-68bbdf0f9173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1d1de27f-51a6-4d19-93b5-ee6f0608f640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breed-add-submit</value>
      <webElementGuid>0b93d069-cd80-4861-b698-ca455c439182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breed_table_add</value>
      <webElementGuid>8e33cf49-71f0-497e-92c4-b8115185011a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>700ae5b2-01f9-40f5-96b1-ab91e405478d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button js-form-submit form-submit border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>8cc50553-d597-436c-add4-aef12dbf438e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>drupal-ajax</value>
      <webElementGuid>17687b7e-97b5-4cc6-a336-66c0774cccc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dog_breed_table&quot;)/div[@id=&quot;edit-dog-breed&quot;]/div[@class=&quot;webform-multiple-add js-webform-multiple-add container-inline&quot;]/input[@id=&quot;edit-dog-breed-add-submit&quot;]</value>
      <webElementGuid>da27df3b-3c8c-4ed3-8a29-dff167ddeef6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
