<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_secondary_segment_performance</name>
   <tag></tag>
   <elementGuidId>9b301e7c-3dbb-4234-9678-a30621d464bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-secondary-segment-performance-lure-coursing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-dog-secondary-segment-performance']/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Lure Coursing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19db07f7-f9ff-4ffa-9a0a-0f54ccb0ef9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-secondary-segment-performance-lure-coursing</value>
      <webElementGuid>ffdfc007-5694-40fe-a815-900308d1e355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ebcd068a-a1c9-4b35-b380-1c3f314c2938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-secondary-segment-performance-lure-coursing</value>
      <webElementGuid>e5a76099-6257-46c0-a967-844fba16a7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_secondary_segment_performance</value>
      <webElementGuid>0dd8aa1f-c1ce-41de-ae70-e5e0e151d199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lure Coursing</value>
      <webElementGuid>469018d4-ae44-4cbc-b4ed-ef9b7dacf571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-radio form-radios</value>
      <webElementGuid>6ff47b34-8a83-4036-af36-a9d4d6ffae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>05ac0f5b-a8fc-4675-b1bb-c4e05eeb99e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-secondary-segment-performance-lure-coursing&quot;)</value>
      <webElementGuid>c5e06b29-fa9d-4d11-bc28-f24e310d7256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-dog-secondary-segment-performance']/div[4]/input</value>
      <webElementGuid>7e33d978-dbbc-47d6-bacb-6dd6046695ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-secondary-segment-performance-lure-coursing']</value>
      <webElementGuid>36be475c-b725-44a2-98b1-25c4d5524ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[12]/div/div/div[4]/input</value>
      <webElementGuid>b762c6c0-f63a-4d3b-8f38-f5369da13d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
