<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_breeditems0dog_primary_number_of_b8805c</name>
   <tag></tag>
   <elementGuidId>4a173aec-056a-4dd4-b749-20e86abee1b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[5]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-breed-items-0-dog-primary-number-of-puppies--EdCPo18CI8w</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-breed-items-0-dog-primary-number-of-puppies']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Change order What primary breed of DOGS do you care for? * # of Adults * # of Breeding Females * # of Puppies Produced Annually * Add new item after item 1 Remove item 1&quot;i] >> internal:label=&quot;# of Puppies Produced Annually\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73694783-dbd0-442e-b268-8bb5348cb0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-number-of-puppies</value>
      <webElementGuid>8adb90ab-0e02-4b08-82a8-55fdc56dd83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>93447493-f32c-4ade-99da-b46359565d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-number-of-puppies--EdCPo18CI8w</value>
      <webElementGuid>49ef1af3-be69-4b20-b64f-5524c81ccab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breed[items][0][dog_primary_number_of_puppies]</value>
      <webElementGuid>f512f896-49c2-4e7b-b415-153bf3a0ad05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>560b583f-c620-4cb6-910e-27475e3d5d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e64a303c-5e47-463c-82dd-3d415fadcaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>948209c2-f2f3-493b-a74c-50db528ac71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0996e145-cbc8-4824-8109-74b2b896c3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>bf3ee234-0918-42a0-b150-dbd84aba15d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1b15327e-3f77-4de1-9477-4ed7efe57452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e18a24ec-05f0-4d69-88fd-4cf65da40424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>76e757a9-2569-4fac-9196-d5111a4fd66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-breed-items-0-dog-primary-number-of-puppies--EdCPo18CI8w&quot;)</value>
      <webElementGuid>8b318087-5d03-4bce-a32f-d635f18e90b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-dog-breed-items--Mfiv3skfHaM']/tbody/tr/td[5]/div/input</value>
      <webElementGuid>bb4623b8-8bc2-45e4-8a6f-0a42ca2da2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-breed-items-0-dog-primary-number-of-puppies--EdCPo18CI8w']</value>
      <webElementGuid>ff720604-d334-4c83-a7c2-1e5b70ff40cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>0ab80ad8-a0a2-4023-adec-9f512adb5997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
