<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dog_breeder_involvement</name>
   <tag></tag>
   <elementGuidId>4aab632c-2c0d-41c1-be68-9c4de7c3fc60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-breeder-involvement-both-breeder-and-participant-in-sanctioned-dog-eventsactivities</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-dog-breeder-involvement']/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Both Breeder AND Participant in sanctioned dog events/activities\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>878837f2-ddb6-4a40-8140-47bbb153dc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breeder-involvement-both-breeder-and-participant-in-sanctioned-dog-eventsactivities</value>
      <webElementGuid>3167b9bf-e17e-4b4d-9b39-0adb406bdecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4172aea3-7241-4e91-895f-5cc79e70bb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breeder-involvement-both-breeder-and-participant-in-sanctioned-dog-eventsactivities</value>
      <webElementGuid>8893db9e-18f8-4fed-b8d3-e099ec004b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breeder_involvement</value>
      <webElementGuid>d2b101e8-344b-417b-bb0e-d450a1b76d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Both Breeder AND Participant in sanctioned dog events/activities</value>
      <webElementGuid>dd8051ab-744c-497d-a555-6df2e81cce6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-radio form-radios</value>
      <webElementGuid>36c152e5-f0bf-4f9e-b839-6e3d05b17d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>19ee52d7-8142-4f90-8a17-39298aa23cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>26ecc249-e881-4ac6-86ab-ca5605c855a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-breeder-involvement-both-breeder-and-participant-in-sanctioned-dog-eventsactivities&quot;)</value>
      <webElementGuid>a8975aa5-7ee1-4e62-8166-1d1d982a77c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-dog-breeder-involvement']/div[3]/input</value>
      <webElementGuid>fdf66d41-efb3-43c0-87ae-870d174f9691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-dog-breeder-involvement-both-breeder-and-participant-in-sanctioned-dog-eventsactivities']</value>
      <webElementGuid>087d6222-70a6-4d0d-9c24-1c51cdcad161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/input</value>
      <webElementGuid>273e78eb-be24-4dbb-b012-c61320fe4c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
