<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cat_breeditems0cat_primary_number_of_c2b1c3</name>
   <tag></tag>
   <elementGuidId>0c5f9365-f9b4-430f-9064-bb1984af4297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[5]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;# of Kittens Produced Annually\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac3b8586-5f0a-410a-b115-47a7facd2ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      <webElementGuid>c9d03ad6-3264-4477-921d-4c09de230edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f42aa842-fd57-4aec-9595-a4c4d0b1770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-breed-items-0-cat-primary-number-of-kittens</value>
      <webElementGuid>a6563ad2-0437-45aa-af23-df32c72d21da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_breed[items][0][cat_primary_number_of_kittens]</value>
      <webElementGuid>c2a13fdb-e2de-4629-9f45-a2ebbe20db98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a183adc8-eb25-417f-adeb-c1ca2868c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f1c1a96-0694-4059-8d6b-f95906f57859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>bbba5d6e-e853-4661-96ec-cbb3b12f6468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c21ae033-7f69-46e9-8afe-b121f9295748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-number required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>5f680280-8b8c-49b8-849f-5b6b4b265a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3ecdc964-510d-4fad-9f04-cc473fcb51be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a73dcbae-d358-4b00-995d-d618a018eb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>a61e8552-4f65-4a5d-9214-f3424a4750a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-breed-items-0-cat-primary-number-of-kittens&quot;)</value>
      <webElementGuid>04d26ead-ab36-4721-86d9-1cd8fe0ffe16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-cat-breed-items']/tbody/tr/td[5]/div/input</value>
      <webElementGuid>1a78bdcf-ac6b-420e-be28-2ad883ac4b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-cat-breed-items-0-cat-primary-number-of-kittens']</value>
      <webElementGuid>dc55082a-4c4a-41b2-a27c-6f1d32938a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>719c495e-222a-4dd2-b9bf-7d03c745aadc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
