<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addresspostal_code</name>
   <tag></tag>
   <elementGuidId>6a408779-327e-457c-90ba-0dca278f31f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-address-postal-code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-address--wrapper']/div/div/div[3]/div[3]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Zip&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fd44d91-9055-4399-b942-b0305bfc70a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-address-postal-code</value>
      <webElementGuid>832e781e-8c1a-4ae0-826b-af7a74035929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ecde29a-b5ca-4411-bd03-dcde9038cb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-address-postal-code</value>
      <webElementGuid>99c6f00f-ea11-4099-9867-e903362dfd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[postal_code]</value>
      <webElementGuid>a97c65eb-b3d9-4314-b361-c4850cd60ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>cc941195-1cb8-4601-9ea2-5ae400875270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5fbda71f-2d11-45b2-bdc2-3a216aab1372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Zip</value>
      <webElementGuid>bcbd4171-cc75-4e2c-89ef-e1d956a214db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text required border-theme-border text-theme-input-text focus:border-theme-focus w-full</value>
      <webElementGuid>1d3ab1d7-85f7-46e1-97ac-60c4f14346da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b667a9d0-6844-4d8f-ad84-338083ec9e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>478d442a-9724-4d40-b633-d08294f62b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-disable-autosubmit</value>
      <webElementGuid>740beba9-bdc7-42d9-b228-38b3a7269d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-address-postal-code&quot;)</value>
      <webElementGuid>1b531a08-5243-4c08-bbc1-37035173cdc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-address--wrapper']/div/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>b52a9333-d3fc-45ed-820e-086b2ce0780f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-address-postal-code']</value>
      <webElementGuid>60b4a819-c215-4ec4-bf12-9b9941c4809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>4c7fd3cb-66a8-4c0f-8906-677017eabbca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
