<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Primary brand of dog food I feed my adults</name>
   <tag></tag>
   <elementGuidId>22b6ac20-617d-4a2a-be1a-3963e4a01f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.js-form-item.form-item.js-form-type-select.form-type-select.js-form-item-dog-primary-dog-food.form-item-dog-primary-dog-food.text-left.mt-4 > label.js-form-required.form-required.text-theme-text.formLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-kennel']/div[6]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Primary brand of dog food I feed my adults *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a56f1ebc-5bab-4928-876f-e601b16cad35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>edit-dog-primary-dog-food</value>
      <webElementGuid>ea67632c-d1c7-443c-9303-c0c1ac96e09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-form-required form-required text-theme-text formLabel</value>
      <webElementGuid>5c8b27d1-6555-483f-bf2d-b3430a7d0ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Primary brand of dog food I feed my adults
    *
  </value>
      <webElementGuid>594d6b9f-d309-48c5-a976-98d4e580cc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-enrollment-kennel&quot;)/div[@class=&quot;js-form-item form-item js-form-type-select form-type-select js-form-item-dog-primary-dog-food form-item-dog-primary-dog-food text-left mt-4&quot;]/label[@class=&quot;js-form-required form-required text-theme-text formLabel&quot;]</value>
      <webElementGuid>df2e551b-3e5b-4d57-ba45-cfdf675599be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-kennel']/div[6]/label</value>
      <webElementGuid>5b98b2cf-5cb9-48e4-a974-bb1dcc5cda98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more items'])[1]/following::label[1]</value>
      <webElementGuid>e36c6025-af26-46f5-9bd3-4bf42a12fd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[125]/following::label[1]</value>
      <webElementGuid>31acec88-b67c-41b4-b548-5019bb52f8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Primary brand of dog food I feed my adults']/parent::*</value>
      <webElementGuid>ff22cf76-bf54-4357-ba58-e319e091a7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label</value>
      <webElementGuid>39703420-cbed-4e78-96c3-92875f9b89b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
