<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Groomer</name>
   <tag></tag>
   <elementGuidId>9913f0bf-482d-47df-be86-3aaf3aa0656a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-dog-primary-segment-show']/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-dog-primary-segment-show >> internal:text=&quot;Groomer *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f33a42bc-8a89-4bd2-bc11-e0c53efd85a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>edit-dog-primary-segment-show-groomer</value>
      <webElementGuid>6afb9237-d59d-46a8-981a-0acdaef3b6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option text-theme-text formLabel</value>
      <webElementGuid>ec9dcb6b-11aa-4ea0-bbee-f4bb0adb28a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Groomer
    *
  </value>
      <webElementGuid>0d425d81-20ad-4e4a-a6a1-c79b8a617b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-primary-segment-show&quot;)/div[@class=&quot;js-form-item form-item js-form-type-radio form-type-radio js-form-item-dog-primary-segment-show form-item-dog-primary-segment-show text-left mt-4&quot;]/label[@class=&quot;option text-theme-text formLabel&quot;]</value>
      <webElementGuid>b147ff10-583f-4cae-b0d9-25bbc35fa100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-dog-primary-segment-show']/div[3]/label</value>
      <webElementGuid>ea5b86cd-7586-4db2-b41f-4f267b110fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::label[1]</value>
      <webElementGuid>2dc3e0d2-374a-40bb-99ff-eba927ceab24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Groomer']/parent::*</value>
      <webElementGuid>a1a94b55-d460-40e2-ba3f-b00d34e14af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div[3]/label</value>
      <webElementGuid>6628f0b6-224c-4a52-a119-9cc4a5180002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
