<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -I have a kennel.Does Not Apply</name>
   <tag></tag>
   <elementGuidId>e9a9cdd1-b5e0-422b-8cb9-254520599407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-kennel-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-part-one']/div[7]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kennel Info\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c4d7a580-fcb6-4bfd-81ce-9cba184656d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-kennel-info</value>
      <webElementGuid>29b42f6b-2dfb-4664-aaa0-77815fd5f43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-kennel-info</value>
      <webElementGuid>3a0cd3c9-65dc-49ae-a286-a42cc193279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kennel_info</value>
      <webElementGuid>2218d54d-c6c1-4cbb-a467-d2566b6e3481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>5f7c563a-155d-4b9f-a5f7-4505b2e0e82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-states</name>
      <type>Main</type>
      <value>{&quot;visible&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;dog&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}],&quot;required&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;dog&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}]}</value>
      <webElementGuid>53b5e2a6-28bd-462f-b036-001c04c4e385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>6c66aed0-dbc6-4a79-80ff-7e65412a319e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9fd05695-33f4-4a6b-bf9a-998738bd2335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>489a4572-1122-4587-beef-3b9a53799411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -I have a kennel.Does Not Apply</value>
      <webElementGuid>e459e83e-3b77-4c8a-a833-f0cf04ee0442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-kennel-info&quot;)</value>
      <webElementGuid>f28ca3b3-34dc-4178-8312-96aa60044b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-part-one']/div[7]/select</value>
      <webElementGuid>1673e6c9-f824-46a3-bcf6-3363304a7d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-kennel-info']</value>
      <webElementGuid>194038a8-bc54-493e-8425-55828fd3c9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>aee498e3-a2d9-4719-add6-cc4c1e185256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>a303da1b-a46b-4e17-aa93-a2c1c58c1fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>63dd7c21-b0a3-469f-b2e4-466a7ec53745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
