<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -I have a cattery.Does Not Apply</name>
   <tag></tag>
   <elementGuidId>34421651-2804-41f2-888e-867bacf46112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cattery-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-part-one']/div[5]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cattery Info\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9cb2714-5499-4009-b5d0-305184ae2fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cattery-info</value>
      <webElementGuid>eeba0dfb-0026-42ac-b982-a3bcee93746b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cattery-info</value>
      <webElementGuid>1f7fb65d-1267-45c8-963c-a7e54457b93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cattery_info</value>
      <webElementGuid>0eeaea3c-1108-4418-baa6-fb4669722c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>1d921bff-1a4b-4c7e-a6e4-c05fd769d871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-states</name>
      <type>Main</type>
      <value>{&quot;visible&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;cat&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}],&quot;required&quot;:[{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;cat&quot;}},&quot;or&quot;,{&quot;.webform-submission-maritz-enrollment-node-301-add-form :input[name=\u0022enrollment_program\u0022]&quot;:{&quot;value&quot;:&quot;both&quot;}}]}</value>
      <webElementGuid>3410efa5-c7a1-47d3-b275-54fb6d33f3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>22ca522d-9441-4d16-9066-3ed8aef7139a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b129ca07-4117-43e8-8149-e011ae560911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3297c85d-4bf9-4901-a2a7-33c79522988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -I have a cattery.Does Not Apply</value>
      <webElementGuid>ac78ee69-b633-42a3-8079-65c156c0f266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cattery-info&quot;)</value>
      <webElementGuid>ac806bc3-b2ce-4353-8fb7-daf8093b5d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-part-one']/div[5]/select</value>
      <webElementGuid>3dc08ee7-4962-4494-bfa3-31e32b00d71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-cattery-info']</value>
      <webElementGuid>46582836-55e2-4b0a-aec3-9ee48e87fabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>083cd46a-bd2f-4e96-9cd9-a8d0ffb55857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>c1144ea1-d144-4d16-a2bd-602f6c03388c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>a4909c02-ff6c-42de-9d7e-bc670e93e7cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
