<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -AcanaAlpoAnnamaetBil-JacBl_cc4de1_3</name>
   <tag></tag>
   <elementGuidId>abce5834-2f6e-4466-8e11-cf815e95d02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-primary-adult-recommendation</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-primary-puppy-recommendation']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-kennel']/div[7]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I recommend feeding adults\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8416cef-03f3-4f6d-91fa-1de2119349ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-primary-puppy-recommendation</value>
      <webElementGuid>e5f7cc18-3cea-40a2-ae21-a0021d1f21c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-primary-puppy-recommendation</value>
      <webElementGuid>450c275c-425a-46cb-a99f-01be57990834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>edit-dog-primary-puppy-recommendation</value>
      <webElementGuid>3d18b34a-4ea2-4d10-a094-21fb4eec8ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>5295df6f-5308-4ab7-a84f-24d17aad30aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e4155713-38a1-422c-9217-44580d2a6f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85bba9c3-d88a-45c8-9624-5a60032c96c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -AcanaAlpoAnnamaetBil-JacBlue BuffaloBlue SealCalifornia NaturalsCanidaeCanine CaviarCastor &amp; PolluxCountry AcresCountry VetDiamondDick Van Pattens Natural BlncEagleEnhanceEukanubaEvangersEvoExclusiveFreshpetFrommHills Science DietHolistic SelectHubbardIamsInnovaJoyKal KanKascoKen L RationKirklandLoyallMerrickNatural BalanceNatures RecipeNuloNutrenaNutri LifeNutri SourceNutro (Max, Natural Choice, Ultra)Old Mother HubbardOld RoyOrijenOther Brand Not ListedOther Canned Product: Not ListedOther Dry Product: Not ListedPedigreePrecisePro PacPro Plan AdultPro Plan FocusPro Plan Puppy DryPro Plan SavorPro Plan SportPurina Beneful DryPurina BeyondPurina Dog Chow DryPurina Moist And MeatyPurina OnePurina Puppy Chow DryPurina Unspec.Purina Veterinary DietsRachel Ray NutrishRed FlannelRiver RunRoyal Canin Veterinary DietsRoyal CanineSensible ChoiceSolid GoldSportmixSportsmans PrideStella &amp; ChewysSunshine MillsTaste Of The Wild (Diamond)Tuffy DryVets Choice Health ExtensionVictorWellnessWysongZignature</value>
      <webElementGuid>dab0b096-fc67-4909-b391-d149c50c0164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-primary-adult-recommendation&quot;)</value>
      <webElementGuid>ee47ef0f-9ba4-43c2-b9a2-31c320e5012e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-kennel']/div[7]/select</value>
      <webElementGuid>d91ed00b-e969-47f2-b3c3-aa99c2f4c06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-dog-primary-adult-recommendation']</value>
      <webElementGuid>70d4fd79-cdbf-4867-af1f-77c0aaff2597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[127]/following::select[1]</value>
      <webElementGuid>828efb42-f040-485e-8b2a-5c9d9d9e2556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[128]/preceding::select[1]</value>
      <webElementGuid>fc564d51-d322-4c2c-bba4-0f5734330cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>bfddf988-e2df-4656-86ae-a4038ce49440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
