<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -7Th Heaven9 LivesA N F (Un_c7f320_1</name>
   <tag></tag>
   <elementGuidId>356939ab-15de-4ad7-b5a2-ffe781fc2889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-cat-primary-adult-recommendation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-enrollment-cattery']/div[4]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I recommend feeding adults\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8fef52f4-1bac-42ae-876b-50b0d78c2eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-cat-primary-adult-recommendation</value>
      <webElementGuid>571061a6-fa7e-4449-91bc-c1416a5a8936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-cat-primary-adult-recommendation</value>
      <webElementGuid>f5c62f83-8dbe-4782-921b-31d35706f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat_primary_adult_recommendation</value>
      <webElementGuid>c7cd6c24-b62e-4d3d-8379-b5c01c36e215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>3bd9a5b3-2e31-48c0-920c-2b9175322105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6357e4aa-a554-460d-aec6-e593d25e19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>061fe6f0-a86c-432c-bc1f-a305fdf6801d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -7Th Heaven9 LivesA N F (Unspecified)A/O BrandsANFAcanaActive LifeAddictionAdm Alliance Nutri.Alley CatAlpo Cat FoodAmoreArcata Pet SuppliesArtemisAtta CatAzmiraBest Feline FriendBil JacBlack GoldBlue BuffaloBlue Seal Kat KrunchiesBreeders Choice Advanced Pet DietBright EyesButtons Bows ChickentBy NatureCalifornia Natural Chicken/RiceCanidaeCanyon Creek Ranch CatCarnation - Unspec.Castor PolluxCat ChowCat MenuCatviarChefs Blend (Dry)Country AcresCountry VetDads Cat FoodDavesDealers PrideDeli-CatDiamondDiamond Chicken SoupDick Van Pattens Natural BlncDura-LifeEagleEarthborn HolisticEnhanceEukanubaEvangersEvolveExcelFamily NutritionalsFancy Feast Cat FoodFarmstyleFelidaeFeline CaviarFreshpetFriskas Cat FoodFrommFussie CatGeneric (No No Name/Unbranded)Go NaturalGoldenGoody Two ChewsGrandma LucysGrandma Maes Country NaturalsGreat LifeHaloHappy CatHappy KittenHeinzHills Science DietHolistic SelectHound And GatosIams Cat FoodInnova Cat FoodIvetKal Kan Cat FoodKascoKat KrunchiesKatg-N-Flocken FlakesKit'n KaboodleKitten ChowKitty KreamKitty Queen Cat FoodKosy KittenKrusesLakeshoreLick Your ChopsLittle RedLone Star Meow For MoreLotus CatLotus KittenMeow MixMerrickMoist MealsMuensterMulliganNaturaNatural BalanceNatural LifeNatural Planet OrganicsNature's ReceipeNatures LogicNatures VarietyNeuraNewmans Own OrganicsNine LivesNow FreshNuloNunn-BetterNurtureNutra Max Cat FoodNutra NuggetNutrenaNutri SourceNutro MaxNutro NaturalOld Blue Tom Cat FoodOld Mother HubbardOrijenParty AnimalPerfect Balance CatPerfection Country KibblePerformPet GoldPet GuardPet MasterPetguardPetite CuisinePrecisePrimalPro PacPro Pet AdultPro Plan Cat Food - AdultPronature HolisticPurina (Unspecified)Purina OnePurr (Canned)Puss-N-BootsRad CatRaw AdvantageReplenishRoyal CaninSamsSavory BlendScience Diet Cat FoodSeminol PremiumSensible Choice Cat FoodShebaSmall BatchSmart CatSojourner FarmsSolid GoldSpecial DinnersSportmixSteves Real FoodSunshine Cat CafeSunshine MillsSupremeTabbyTamiami Cat FoodTaste-T-ChewTender Vittles MoistThe Goodlife RecipeThriveTiki CatTimberwolfTriump Cat FoodTuffyV/F Veterinarian CompleteVerusVets Choice Health ExtensionVf CompleteVita RxVital EssentialVitalityWellnessWeruvaWestern SunWhiskasWysongZiwipeakZupreem</value>
      <webElementGuid>b9b8e51d-55d5-4db7-bf1f-5ac262d6280f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-primary-adult-recommendation&quot;)</value>
      <webElementGuid>b27c125e-e994-4a63-ad61-3fa7ab971d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-enrollment-cattery']/div[4]/select</value>
      <webElementGuid>a5ec94d0-97ad-4d03-b91e-612097abb710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-cat-primary-adult-recommendation']</value>
      <webElementGuid>8ba79d58-faf9-47fe-8e5a-77fc99943f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::select[1]</value>
      <webElementGuid>d573e5fc-21b2-4bb6-be87-c630e9c466ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[17]/preceding::select[1]</value>
      <webElementGuid>728daa9e-c043-4e81-b2a2-dcc3c2817896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>5c3d23e2-89cc-41e1-940d-a851964330fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
