<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -AffenpinscherAfghan HoundA_ef929c</name>
   <tag></tag>
   <elementGuidId>264c6a1f-a72b-4d4e-a14c-e339ed5da2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-dog-breed-items-0-dog-primary-breed</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-drupal-selector = 'edit-dog-breed-items-0-dog-primary-breed']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='edit-dog-breed-items']/tbody/tr/td[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;What primary breed of DOGS do you care for?\n    *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2b23ba7-92e8-438a-ac05-647795e73ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-breed</value>
      <webElementGuid>ce475fd7-c32d-45b1-aa25-342b32c6ad88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-dog-breed-items-0-dog-primary-breed</value>
      <webElementGuid>1c93b707-3eee-4224-9f7f-6553053c0f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dog_breed[items][0][dog_primary_breed]</value>
      <webElementGuid>fc5d75a2-be16-403e-82c4-f5c11daf370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select required border-theme-border text-theme-input-text w-full</value>
      <webElementGuid>8ef814bf-a582-40d9-9418-3a34caf7c1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>06108d2c-5dda-4b53-a1a9-1bb9e068e76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c21ec3b-35a5-4b8d-9f96-4d57e848664f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -AffenpinscherAfghan HoundAinuAiredale TerrierAkbash DogAkitaAlaskan Klee KaiAlaskan MalamuteAlpine DachsbrackeAmerican BulldogAmerican CoonhoundAmerican EskimoAmerican FoxhoundAmerican Hairless TerrierAmerican Leopard HoundAmerican Pit Bull TerrierAmerican Rabbit HoundAmerican Staffordshire TerrierAmerican Water SpanielAnatolian Shepherd DogAnglo-Francais De Moyen VenerieAnglo-Francais De Petite VenerieAppenzellerAriegeoisAustralian Cattle DogAustralian KelpieAustralian ShepherdAustralian TerrierAzawakhBarbetBasenjiBasset Artesian NormandBasset Bleu De GascogneBasset Fauve De BretagneBasset HoundBavarian Mountain HoundBeagleBeagle HarrierBearded CollieBeauceronBedlington TerrierBelgian GroenendaelBelgian LaekenoisBelgian MalinoisBelgian SheepdogBelgian TervurenBergamascoBerger De PyreneesBerger PicardBernese Mountain DogBichon FriseBillyBlack Forest HoundBlack Mouth CurBlack Russian TerrierBlk &amp; Tan CoonhoundBloodhoundBluetick CoonhoundBoerboelBologneseBorder CollieBorder TerrierBorzoiBoston TerrierBouvier Des FlandresBoxerBoykin SpanielBracco ItalianoBraque D'AuvergneBraque Du BourbonnaisBraque Francais, De Grande TailleBraque Francais, De Petite TailleBraque Saint-GermainBriardBriquet Griffon VendeenBrittanyBrussels GriffonBull TerrierBull Terrier (American)BulldogBullmastiffCIRNECO DELL ETNACairn TerrierCamus CurCanaan DogCanadian CurCanadian Eskimo DogCane CorsoCarolina DogCaucasian Mountain DogCavalier-King Charles SpanielCentral Asian Shepherd DogCesky TerrierChart PolskiChesapeake Bay RetrieverChien D'ArtoisChien Francais Blanc et NoirChien Francais Blanc et OrangeChien Francais TricoloreChihuahuaChinese CrestedChinese Shar-PeiChinookChow ChowClumber SpanielCocker SpanielCollieCoton De TulearCurly Coated RetrieverDEUTSCH DRAHTHAARDEUTSCH KURZHAARDachshundDalmatianDandie DiNmont TerrierDanish BroholmerDenmark FeistDeutsch LanghaarDeutsche BrackeDoberman PinscherDogo ArgentinoDogue De BordeauxDrentse PatrijshondDreverDunkerDutch ShepherdEast Siberian LaikaEnglish BulldogEnglish Cocker SpanielEnglish CoonhoundEnglish FoxhoundEnglish PointerEnglish SetterEnglish ShepherdEnglish Springer SpanielEnglish Toy SpanielEntlebucherEpagneul Bleu De PicardieEpagneul PicardEpagneul Pont-AudemerEstonian HoundEstrela Mountain DogEurasianField SpanielFinnish HoundFinnish LapphundFinnish SpitzFlat Coated RetrieverFox TerrierFrench BulldogFrench SpanielGerman Longhaired PointerGerman PinscherGerman Shepherd DogGerman Shorthaired PointerGerman SpanielGerman Wirehaired PointerGiant SchnauzerGlen of Imaal TerrierGolden RetrieverGordon SetterGrand Anglo-FrancaisGrand Basset Griffon VendeenGrand Bleu De GascogneGrand Gascon-SaintongeoisGrand Griffon VendeenGreat DaneGreat PyreneesGreater Swiss Mountain DogGreenland DogGreyhoundGriffon Fauve De BretegneGriffon NivernaisHamiltonstovareHanoverian HoundHarrierHavana Silk DogHavaneseHovawartIbizan HoundIcelandic SheepdogIrish Red &amp; White SetterIrish SetterIrish TerrierIrish Water SpanielIrish WolfhoundItalian GreyhoundJagdterrierJapanese ChinJindoKaiKangal DogKarelian Bear DogKeeshondKerry Blue TerrierKomondorKooikerhondjeKrasky OvcarKromfohrlanderKuvaszLabrador RetrieverLagotto RomangnoloLakeland TerrierLeonbergerLhasa ApsoLouisiana Catahoula Leopard DogLowchenLundehundMalteseManchester TerrierMaremma SheepdogMastiffMiniature American ShepherdMiniature Australian ShepherdMiniature Bull TerrierMiniature PinscherMiniature SchnauzerMiscMountain CurMudiMullin's FeistMunsterlander: LargeMunsterlander: SmallNeapolitan MastiffNederlandse KooikerhondjeNew Guinea Singing DogNewfoundlandNorbottenspetsNorfolk TerrierNorwegian BuhundNorwegian ElkhoundNorwegian LundehundNorwich TerrierNova Scotia Duck Tolling RetrieverOld Danish Bird DogOld English SheepdogOriginal Mountain CurOther: Breed Not ListedOtterhoundOwczarek PodalanskiPapillonParson Russell Terrier (Formerly Jack)Patterdale TerrierPekingesePerdiguero De BurgosPerdiguero NavarroPeruvian Inca OrchidPetit Basset Griffon VendeenPetit Bleu De GascognePetit Gascon-SaintongeoisPetit Griffon Bleu De GascognePharaoh HoundPlott HoundPointerPoitevinPolish HoundPolish Lowland SheepdogPolski Owczarek NizinnyPomeranianPoodlePorcelainePortuguese Podengo PequenoPortuguese PointerPortuguese Water DogPudelpointersPugPuliPumiPyrenean ShepherdRat TerrierRedbone CoonhoundRhodesian RidgebackRottweilerRussell TerrierRusso-European LaikaSalukiSamoyedSarplaninacSchapendoesSchipperkeScottish DeerhoundScottish TerrierSealyham TerrierShetland SheepdogShiba InuShih TzuSiberian HuskySilken WindhoundSilky TerrierSkye TerrierSloughiSlovak CuvacSmooth Fox TerrierSoft Coated Wheaten TerrierSouth Russian OvcharkaSouthern Blackmouth CurSpaniel- SussexSpanish Hound- LargeSpanish Hound- SmallSpanish MastiffSpanish Water DogSpinone ItalianoSporting-OtherSt BernardStabyhounStaffordshire Bull TerrierStandard SchnauzerStephens' CurStumpy Tail Cattle DogSussex SpanielSwedish LapphundSwedish VallhundTeddy Roosevelt TerrierThai RidgebackThornburg FeistTibetan MastiffTibetan SpanielTibetan TerrierTosa KenToy Fox TerrierTreeing CurTreeing FeistTreeing Tennessee BrindleTreeing Walker CoonhoundVerein Deutsch DrahthaarVizslaWeimaranerWelsh Corgi-CardiganWelsh Corgi-PembrokeWelsh Springer SpanielWelsh TerrierWest Highland White TerrierWest Siberian LaikaWhippetWhite ShepherdWirehaired Fox TerrierWirehaired Pointing GriffonWirehaired VizslaXoloitzcuintliYorkshire Terrier</value>
      <webElementGuid>41982c5a-1131-4090-9185-4be1dfbc83c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-breed-items-0-dog-primary-breed&quot;)</value>
      <webElementGuid>87d7cd7d-dd06-4d36-9978-51b72d794765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='edit-dog-breed-items']/tbody/tr/td[2]/div/select</value>
      <webElementGuid>9e58ffff-f5e8-40b9-b74e-723e031f2981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-dog-breed-items-0-dog-primary-breed']</value>
      <webElementGuid>b2240d64-809e-4381-9f0c-0719f6d6e010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[115]/following::select[1]</value>
      <webElementGuid>71e59d82-a6be-4d59-8444-1fe0fad99741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[116]/preceding::select[1]</value>
      <webElementGuid>524f799b-09c0-4d56-abcf-b6095f5b7b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/select</value>
      <webElementGuid>9f9a5d6f-7951-482a-a59d-d0a53e3eb9ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
