<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GetTestResult</name>
   <tag></tag>
   <elementGuidId>2d132860-79f6-4ca5-9221-965df3db3c66</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;id\&quot;: ${Obj},\r\n    \&quot;Name\&quot;: ${ObjArr},\r\n    \&quot;Empty\&quot;: ${empty}\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic e3tVc2VybmFtZX19OjgxYWI1ZTZhLWM2MjktNDU3Yy04ZWI3LWNkZmVhYzQ2NTZmMQ==</value>
      <webElementGuid>da1dd06b-4897-477f-8965-94abbf930349</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://testops.katalon.io/api/v1/run-configurations/${id}/execute</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.id</defaultValue>
      <description></description>
      <id>710a2312-7a5c-4810-9f22-0a189a5ba737</id>
      <masked>false</masked>
      <name>id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.Obj</defaultValue>
      <description></description>
      <id>fdc8536e-c894-4318-89ca-453bed6c4def</id>
      <masked>false</masked>
      <name>Obj</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.ObjArr</defaultValue>
      <description></description>
      <id>8bf0a6f2-2dc9-4f87-b303-199a9547f6cd</id>
      <masked>false</masked>
      <name>ObjArr</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.empty</defaultValue>
      <description></description>
      <id>d6ab5b30-60b3-409d-9b23-351df2fbc3fa</id>
      <masked>false</masked>
      <name>empty</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
