<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Import</name>
   <tag></tag>
   <elementGuidId>b2bdf454-3b42-4edb-bc5a-c670b417c919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1j5wdaa > div.css-1y0i9u2 > div.css-1b9h7z9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Import&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4fe4895-25c1-4272-9a2d-80c6cff3f35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dvtl-tour-id</name>
      <type>Main</type>
      <value>NoteGridViewImportCard</value>
      <webElementGuid>bd085b3b-a4a2-498a-a8e2-7206101de8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>224</value>
      <webElementGuid>425d6c9d-549a-47e6-ad07-64d433b109bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>b05caeeb-f1d7-4d1c-a18d-ea0c9925ca3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1b9h7z9</value>
      <webElementGuid>af9b9899-ce8b-43ac-a620-123caf073dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import</value>
      <webElementGuid>f8935a09-3092-4815-84c7-c653a4ba0b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;css-e69dqy&quot;]/div[@class=&quot;css-e69dqy&quot;]/div[@class=&quot;css-e5j86h&quot;]/div[@class=&quot;css-a4mcd5&quot;]/div[@class=&quot;css-1v6v3k5&quot;]/div[@class=&quot;css-1tj9cbb&quot;]/div[@class=&quot;css-0&quot;]/div[1]/div[1]/div[@class=&quot;css-1itahzc&quot;]/div[1]/div[1]/div[@class=&quot;ReactVirtualized__Grid&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[2]/div[1]/div[@class=&quot;css-1j5wdaa&quot;]/div[@class=&quot;css-1y0i9u2&quot;]/div[@class=&quot;css-1b9h7z9&quot;]</value>
      <webElementGuid>6d5f28b8-b0c0-4bb0-b631-df904137df92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>6973b227-103d-4b39-a0c6-54b2bd954d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@type='row'])[2]</value>
      <webElementGuid>522433be-25cb-48cd-b041-671d74cdb2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::div[5]</value>
      <webElementGuid>2c01d907-6e2b-4f61-a3ee-88381938ecfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::div[21]</value>
      <webElementGuid>aff31db9-a0ee-4a45-8fbd-c46f52baf0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>1d18a95b-ac56-4d96-bbba-b86d003eac3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
