<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Publisher</name>
   <tag></tag>
   <elementGuidId>4c6fda71-4eae-490a-9f9f-f5ffcd2da8ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;Layout_nintex-layout__1cXXD&quot;]/section[@class=&quot;TemplateDetail_nintex-solution-template-detail-icons__jCH8u&quot;]/div[@class=&quot;TemplateDetail_container__CsLHu&quot;]/div[@class=&quot;TemplateDetail_nintex-solution-template-detail-icons-section__EuwdB&quot;]/div[@class=&quot;Group_nintex-solution-template-detail-icon-right-section__n8jRr&quot;]/div[@class=&quot;Group_nintex-gallery-icon-description__xedls&quot;]/p[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h5[text()='Publisher']/parent::div/following-sibling::div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nintex&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>abfe6227-6e86-4a46-ad34-5fc93a84761a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nintex</value>
      <webElementGuid>748cd7c7-b21d-4c3d-9acf-da9e934e25c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;Layout_nintex-layout__1cXXD&quot;]/section[@class=&quot;TemplateDetail_nintex-solution-template-detail-icons__jCH8u&quot;]/div[@class=&quot;TemplateDetail_container__CsLHu&quot;]/div[@class=&quot;TemplateDetail_nintex-solution-template-detail-icons-section__EuwdB&quot;]/div[@class=&quot;Group_nintex-solution-template-detail-icon-right-section__n8jRr&quot;]/div[@class=&quot;Group_nintex-gallery-icon-description__xedls&quot;]/p[1]</value>
      <webElementGuid>8c51afea-6698-49f2-b239-40a85f36ca3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section[2]/div/div[2]/div[2]/div[2]/p</value>
      <webElementGuid>fb4fe4d0-fdea-4512-a4aa-37c270eb5390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publisher'])[1]/following::p[1]</value>
      <webElementGuid>b5977398-97cb-4198-b180-52ac48815ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::p[1]</value>
      <webElementGuid>04cffea7-0d9b-4efa-b745-b808ac763aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Downloads'])[1]/preceding::p[2]</value>
      <webElementGuid>c7ff5397-c36d-4b8f-9e42-3d993f3f0fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/preceding::p[4]</value>
      <webElementGuid>21de80f7-3eef-44fe-9f13-ce3b1a7da4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nintex']/parent::*</value>
      <webElementGuid>c500376e-1d5d-41c4-b9fe-57f4096953f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>b6349342-b53e-4f62-ac8d-77dffbcd7a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
