<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2000</name>
   <tag></tag>
   <elementGuidId>ac3ee889-dc3b-4d1d-a3ef-a8cf8fbc491a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//kendo-calendar[@id='kendo-calendarid-0']/kendo-calendar-navigation/kendo-virtualization/ul/li[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-calendar-navigation-marker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=list >> internal:text=&quot;2000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5de9474d-77a2-4da3-8348-2be833d59d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-calendar-navigation-marker</value>
      <webElementGuid>32684b0f-65b9-425c-84af-f2ca19d405b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>2487d201-d52f-41bc-9877-fe07d339aeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kendo-calendarid-0&quot;)/kendo-calendar-navigation[@class=&quot;k-calendar-navigation&quot;]/kendo-virtualization[@class=&quot;k-flex k-content k-scrollable&quot;]/ul[@class=&quot;k-reset&quot;]/li[2]/span[@class=&quot;k-calendar-navigation-marker&quot;]</value>
      <webElementGuid>247addf6-9e27-49e6-a4f9-c6c8b9bd6863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Kendo/Page_Calendar Component - Overview  Kendo U_cd97ce/iframe_default_demo-example-sc-grlnui-1 cddDli</value>
      <webElementGuid>fb754be6-0aa8-4b73-9e26-989962cd1fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//kendo-calendar[@id='kendo-calendarid-0']/kendo-calendar-navigation/kendo-virtualization/ul/li[2]/span</value>
      <webElementGuid>a438f9b3-fe4e-456a-b064-fd7c4391019c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[3]</value>
      <webElementGuid>af2b06df-985e-4d1a-8f29-a29a6445e2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 2024'])[1]/preceding::span[15]</value>
      <webElementGuid>4c52fa16-a64b-4fce-b17e-c5aaaf207e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2000']/parent::*</value>
      <webElementGuid>3cb11d28-faf4-4238-b83d-4b5691dfa4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>218607a6-175c-4c65-a6ab-9e74d0544d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2000' or . = '2000')]</value>
      <webElementGuid>c20b5779-58fb-45b4-8053-88000da631b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
