<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_308.52</name>
   <tag></tag>
   <elementGuidId>bdba1ecf-9816-4d1f-aa27-26d3d88703ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.result-data-large.number.result-data-value.upload-speed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;308.52&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e609db2b-5363-4ddb-bbdf-dda1de700efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-upload-status-value</name>
      <type>Main</type>
      <value>0.31</value>
      <webElementGuid>6fdbc6f7-4372-44d7-87d2-4526b66bf039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-data-large number result-data-value upload-speed</value>
      <webElementGuid>fce197f9-0abe-4fec-a033-ad532168a644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>308.52</value>
      <webElementGuid>669bca8e-954e-429e-b072-515e2be6c505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;pre-fold mobile-test-complete&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;pure-g&quot;]/div[@class=&quot;pure-u-custom-speedtest&quot;]/div[@class=&quot;speedtest-container main-row&quot;]/div[@class=&quot;main-view&quot;]/div[1]/div[@class=&quot;result-area result-area-test&quot;]/div[1]/div[@class=&quot;result-container clearfix&quot;]/div[@class=&quot;result-container-speed result-container-speed-active&quot;]/div[@class=&quot;result-container-data&quot;]/div[@class=&quot;result-item-container result-item-container-align-left&quot;]/div[@class=&quot;result-item result-item-first-class result-item-upload updated test-mode-multi&quot;]/div[@class=&quot;result-data u-align-left&quot;]/span[@class=&quot;result-data-large number result-data-value upload-speed&quot;]</value>
      <webElementGuid>c7e56d7e-6c54-4ae1-a770-89a29e574ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div/div[2]/div/div[2]/span</value>
      <webElementGuid>ec460881-b6ca-4c01-910e-3aaa1d531797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mbps'])[2]/following::span[1]</value>
      <webElementGuid>ba7f977b-f695-426e-973a-a734b95b451e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ping'])[1]/preceding::span[1]</value>
      <webElementGuid>fa798939-71a4-424e-bab4-35d0f808a4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ms'])[1]/preceding::span[2]</value>
      <webElementGuid>24411560-1806-44b7-a8bb-8196d61436dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='308.52']/parent::*</value>
      <webElementGuid>cd1c8397-6a19-45f5-93a1-bee79a585deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/span</value>
      <webElementGuid>af9dc310-983f-46d9-b42f-1d98a7a7ca28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
