<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_252.80</name>
   <tag></tag>
   <elementGuidId>0a215107-af85-45ea-9e67-b2933612fc2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.result-data-large.number.result-data-value.download-speed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;252.80&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>331f802b-72bb-4d25-869e-3866623e6fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-download-status-value</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>9c5e0846-1171-47a7-841d-a13b4688d546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-data-large number result-data-value download-speed</value>
      <webElementGuid>0a5182fa-a75e-4890-ba06-df1c3a1d3b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>252.80</value>
      <webElementGuid>8aeb2e52-ca74-4f29-8ecd-a308210dcbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;pre-fold mobile-test-complete&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;pure-g&quot;]/div[@class=&quot;pure-u-custom-speedtest&quot;]/div[@class=&quot;speedtest-container main-row&quot;]/div[@class=&quot;main-view&quot;]/div[1]/div[@class=&quot;result-area result-area-test&quot;]/div[1]/div[@class=&quot;result-container clearfix&quot;]/div[@class=&quot;result-container-speed result-container-speed-active&quot;]/div[@class=&quot;result-container-data&quot;]/div[@class=&quot;result-item-container result-item-container-align-center&quot;]/div[@class=&quot;result-item result-item-first-class result-item-download updated test-mode-multi&quot;]/div[@class=&quot;result-data u-align-left&quot;]/span[@class=&quot;result-data-large number result-data-value download-speed&quot;]</value>
      <webElementGuid>66802287-f178-4b88-8a2f-35f38246fc35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div[2]/div[3]/div[3]/div/div[3]/div/div/div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>ae38376f-863e-4932-ab26-9e77025a6389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mbps'])[1]/following::span[1]</value>
      <webElementGuid>6fea2adf-c4e4-4122-9062-4c95ccfbfb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mbps'])[2]/preceding::span[1]</value>
      <webElementGuid>c4808575-9034-4cde-b920-e077c50194c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='252.80']/parent::*</value>
      <webElementGuid>2d3aa651-96a3-4b39-890f-d0c64302f46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>ee2ec639-ba44-47e0-a9a5-36905f527f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
