<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>24862dae-8cc2-4ad2-bfd1-0f020e6ed20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.jss193.jss205.jss194.jss206.jss129</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;country-selector-submit-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58e0dfa5-c1e5-4bba-9452-6f28da393fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root jss193 jss205 jss194 jss206 jss129</value>
      <webElementGuid>5872dfe1-0033-4a0d-8cb3-216a8632c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b43b46e3-1db5-4742-9e86-9a02227e3d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9520a124-2e0f-417d-9fb2-dc2888b19ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>country-selector-submit-button</value>
      <webElementGuid>7aa027fd-b06c-4627-83b8-2d603d89c509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>1499a411-572d-4d9b-8423-c2728071b0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;jss109&quot;]/div[@class=&quot;jss113 jss114&quot;]/div[@class=&quot;jss117 jss119 jss118&quot;]/div[@class=&quot;jss115 jss116&quot;]/div[@class=&quot;MuiBox-root jss130 jss120&quot;]/div[@class=&quot;MuiBox-root jss131 jss121&quot;]/div[@class=&quot;MuiBox-root jss133 jss123&quot;]/form[@class=&quot;jss125&quot;]/button[@class=&quot;MuiButtonBase-root jss193 jss205 jss194 jss206 jss129&quot;]</value>
      <webElementGuid>803fbd55-c8a2-44f6-bf63-8b01eaaef5cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>2ce917ee-6572-4a9d-863c-d8af658948af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div/div/div/div/div[2]/form/button</value>
      <webElementGuid>ae589930-0463-446c-8030-83ef196d2a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a language'])[1]/following::button[1]</value>
      <webElementGuid>0fe1796d-a6d2-4a4c-8ec9-d215736cfcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c482b3ce-eeef-4951-afca-36a6d505a0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7eaad763-52c7-43e3-89ab-e380f4a4bcdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
