<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>49b26b55-97a0-4839-91ad-31e7a82ecaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#mui-component-select-country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-labelledby=&quot;country-label&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;menu-country&quot;)/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-country > div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0a54274-d296-4b95-8b5c-42a4b7f91e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b09315ed-9710-4958-bfd0-a67d2185b256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-country&quot;)/div[1]</value>
      <webElementGuid>c34b9f94-bb68-4aba-8bf7-cd7f7c5e77cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-country']/div</value>
      <webElementGuid>0b8b5d06-00cc-4009-b4ec-648cbecf67a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>02556da1-d970-4877-aabb-b27c9abfb91e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
