<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Germany</name>
   <tag></tag>
   <elementGuidId>0d14625e-967f-47dc-940b-3fc7f06856c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-country']/div[3]/ul/li[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Not selected germany&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0a52881d-0eda-4d0f-83a0-ebfc5fd5f5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss223 jss225 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-divider MuiListItem-button</value>
      <webElementGuid>86fe2011-de5f-4528-bf4c-6b4bdb999b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>701e14d1-6492-4ff8-b316-77ee952ceafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>4c244be7-2cbd-4c35-add6-3ece754f5d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35281847-a503-4a20-8550-b3dca5606223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Not selected germany</value>
      <webElementGuid>a6d67419-1812-41fb-a777-dce42edf69f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>country-dropdown__item</value>
      <webElementGuid>10e017cf-9334-46e0-b3e1-d88effb59312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Germany</value>
      <webElementGuid>e1fec45c-6217-4e4c-8ed9-d975f01bfc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Germany</value>
      <webElementGuid>38f0be2a-842c-46ff-ab92-c4273ec4be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-country&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-root MuiMenu-paper jss146 jss155 jss163 jss165 MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root jss164 jss166 MuiMenu-list&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss223 jss225 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-divider MuiListItem-button&quot;]</value>
      <webElementGuid>8a8c7f20-b40e-4b22-8bb6-eac3bf6dfe61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-country']/div[3]/ul/li[11]</value>
      <webElementGuid>3b16f0b1-11f1-435c-9130-49d7425f703f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::li[12]</value>
      <webElementGuid>1b0b95d2-d9d1-4470-98ce-4d655c06e82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::li[12]</value>
      <webElementGuid>25dc39f4-96c3-4127-bbd2-c88842c65718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>4fc90adf-8f23-47aa-a93a-8cebe48e4d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Germany' or . = 'Germany')]</value>
      <webElementGuid>66efe4d0-edd1-40ae-aca2-4419b2001e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
