<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Update</name>
   <tag></tag>
   <elementGuidId>f30ecd34-fd04-40f8-8080-c3d954913362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.UpdateCityModal__update-btn___2qmN1.UpdateCityModal__btn___oMW5n</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='update-city-modal']/div/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Update&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b4f73f9-2a95-41d7-8832-40033230bdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UpdateCityModal__update-btn___2qmN1 UpdateCityModal__btn___oMW5n</value>
      <webElementGuid>af869fcd-048b-4201-8ed9-5af84fb4a5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auto-updatecity-update</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78d9710c-26e8-4521-bbb9-696161acdc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>cab34b98-92d8-4a78-931d-ff3979bd80e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update-city-modal&quot;)/div[@class=&quot;UpdateCityModal__modal-body___H98MG&quot;]/div[@class=&quot;UpdateCityModal__update-confirm___1iV9N&quot;]/div[@class=&quot;UpdateCityModal__update-btn___2qmN1 UpdateCityModal__btn___oMW5n&quot;]</value>
      <webElementGuid>8e8234ca-8511-45d7-a4fd-5b42f786d998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='update-city-modal']/div/div[3]/div[2]</value>
      <webElementGuid>774cb15a-49d3-46b0-b0f9-b7fc699d52d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[1]</value>
      <webElementGuid>1c39ceb4-bcac-47a0-a0c7-1f2d09cb162e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kanchipuram'])[1]/following::div[3]</value>
      <webElementGuid>4f46ccfd-413a-4519-b345-312d5a521bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medicines'])[1]/preceding::div[4]</value>
      <webElementGuid>7862aeca-ac5c-4aa4-a274-1f38f98a396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lab Tests'])[1]/preceding::div[5]</value>
      <webElementGuid>36b89933-a6d2-431d-b407-1f1812f7c8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>df9a167a-7263-4da1-ad95-e02d62c45a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>7cd3c5ef-5d2b-4003-9f54-11341ac18a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>4754616a-3f8a-4e49-b431-6379ed267b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
