<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Your mobile number or email_phone</name>
   <tag></tag>
   <elementGuidId>0544cdd9-75b7-4ac9-b662-5279a6d6db1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;inputField_login&quot;] >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae06d0b5-5708-48ce-bfc9-793bc16780b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a796b08-71e3-43a6-a16e-a4d0a613171a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputField__inputBox__f9eyX</value>
      <webElementGuid>7f9d2156-cefe-4381-8284-2e4b88e086d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>7f7be60d-808e-4ffa-b7e3-8e9ec4c698ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex alignCenter justifyCenter Dialog__overlay__qXgA1 Dialog__open__z4cbA&quot;]/div[@class=&quot;Dialog__container__VfbCm&quot;]/div[@class=&quot;padding-0-24&quot;]/div[@class=&quot;Auth__container__nVizI flex&quot;]/div[@class=&quot;Auth__rightContainer__RI0XX&quot;]/div[@class=&quot;Auth__authContainer__sE45H&quot;]/div[@class=&quot;Auth__paddingAuth__VUrFH flex flexColumn justifyBetween&quot;]/div[1]/div[@class=&quot;Auth__marginBottom16__tg0Up&quot;]/div[@class=&quot;flex flexColumn InputField__inputParent__GoM5F&quot;]/div[@class=&quot;l5Regular textSecondary  InputField__borderBottomPrimary__wV6M8 InputField__focused__qoCpg&quot;]/div[@class=&quot;flex justifyBetween&quot;]/input[@class=&quot;InputField__inputBox__f9eyX&quot;]</value>
      <webElementGuid>327d63bc-487e-45ee-93c3-55cca55dfbe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
      <webElementGuid>3f525681-15da-446d-a8cb-ed6def49fa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>360bdcd1-7a05-4fd6-8514-4b4a1133aa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>1823ed49-fbe5-4c3b-9562-f7be1d97a92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phone']</value>
      <webElementGuid>3173a319-4172-4c66-89bd-bdf4e2572db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
