<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zunhebotto_name</name>
   <tag></tag>
   <elementGuidId>8cb1ddc0-b3aa-488a-9328-1aa17d8fbf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#srchBarShwInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='srchBarShwInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search for Medicines and Health Products&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96b773a5-2149-4c8f-833c-3399b55e0ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a81e4e98-9757-43c1-9b5b-7b345b7192df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>srchBarShwInfo</value>
      <webElementGuid>bbd5f669-911a-4228-a8e9-d0d3575bac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for Medicines and Health Products</value>
      <webElementGuid>5fa190aa-bbfe-41a0-91fb-e1d5843eca6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14209094-5040-46ad-91a4-5d273cf5896a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ff83b852-0d06-41f7-b344-d53547187efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auto-search-bar</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d0cda44-2545-4925-8f89-78c98ff0aece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__search-input___3I6VS</value>
      <webElementGuid>e34a3fd8-d249-4217-9295-b0d110cdbab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srchBarShwInfo&quot;)</value>
      <webElementGuid>0603a1e0-397b-4c56-98c0-91fe62a3262f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='srchBarShwInfo']</value>
      <webElementGuid>67e53706-5876-4a9a-9b24-82fcd3900dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='srchBarShwInfo-form']/input</value>
      <webElementGuid>05974aa3-fe23-46ed-b405-49ac39b19601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>260e0209-fe15-4d72-83b6-514d84ab0240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'srchBarShwInfo' and @placeholder = 'Search for Medicines and Health Products' and @name = 'name']</value>
      <webElementGuid>a1a6d1e8-590f-428a-a6e4-87de151f3125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
