<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bitte gib Deine Postleitzahl, Region _31f5d3</name>
   <tag></tag>
   <elementGuidId>66df7c02-93c4-4c22-8c3a-d35fd2bb9f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'dealer-agent-search' and @name = 'dealerAgentSearch' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dealer-agent-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dealer-agent-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Retail Partner auswählen. Bitte gib Deine Postleitzahl, Region oder den Ort ein.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59cd1bb5-72a0-4b4f-94f9-cc3ddc1ed207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c60a778-42c3-4c77-98b4-37e3b23bd296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c073458a-8947-4919-8a17-a6b1fdd3a75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dealer-agent-search</value>
      <webElementGuid>220b944f-42a2-4924-8f16-4eaa7dbb73c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dealerAgentSearch</value>
      <webElementGuid>10280874-3959-403f-8f46-dc9ac05b77e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb0055ca-7fb6-42a9-bd29-eb666a80599f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss889 jss897 MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>4fe73279-b21a-4e2d-b066-a1a3fc1a01cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>06bdc258-7dbd-455e-a6c1-72e2aaa07888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>53a0f643-d937-4193-acac-a6ab08b70fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b68e3a8f-f9a4-4eba-99f3-467110b4693e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Retail Partner auswählen. Bitte gib Deine Postleitzahl, Region oder den Ort ein.</value>
      <webElementGuid>3e47313a-b694-44fc-bd15-036c907bec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dealer-agent-search-popup</value>
      <webElementGuid>101e3561-3289-40b6-b8d1-8850ec8527e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealer-agent-search&quot;)</value>
      <webElementGuid>9438700f-4cc8-4e1b-b8c8-8f1ec85657bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dealer-agent-search']</value>
      <webElementGuid>02e3db07-13ec-4482-a3f4-e7feb7243c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ecb6b027-3cd8-4ab5-8b58-fdeac384ee80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>17346c57-a5ca-461a-9b50-fd0aa01f86cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dealer-agent-search' and @name = 'dealerAgentSearch' and @type = 'text']</value>
      <webElementGuid>dfe2259e-b574-4b3f-9e14-0d420deaef77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
