<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Mail_personalInfo.email</name>
   <tag></tag>
   <elementGuidId>30b0deb2-9006-4472-aba2-5b26a5d83d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='test-drive-personal-info-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-drive-personal-info-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-Mail&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31e4f23c-4e7d-4b51-be2e-bf3cbeb4b822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac171148-01bf-4b20-9603-d8e1237020ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-drive-personal-info-email</value>
      <webElementGuid>a0be054a-178a-47b9-84e1-7c02f16f330d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.email</value>
      <webElementGuid>83d88671-10c0-4dbe-a6ec-fff80db2ebb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af5c67a9-5527-4b9b-b2f0-b4b6d6307d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>E-Mail</value>
      <webElementGuid>71fb0257-31f5-4e0c-a93e-9591c06b8e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss889 jss1027 MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>2c015f72-9f4d-4571-8988-08cb9650754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-drive-personal-info-email&quot;)</value>
      <webElementGuid>d34a198f-05ae-4be7-9604-8cad4c4567b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='test-drive-personal-info-email']</value>
      <webElementGuid>cf4e59b4-1135-4675-b09d-0191dbc5a53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>c98b99a1-f552-486d-807a-0553c10f24fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>fdaf9bd5-0ebe-4893-85ea-bff6afdaa740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'test-drive-personal-info-email' and @name = 'personalInfo.email' and @type = 'text']</value>
      <webElementGuid>b53dc10b-d058-44f5-8db6-a3bce82a4b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
