<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nachname_personalInfo.lastName</name>
   <tag></tag>
   <elementGuidId>c45b8ad9-37f6-486d-802b-1fb683c7d4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='test-drive-personal-info-last-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-drive-personal-info-last-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nachname&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1d657d9-bf1d-4f58-81df-9cd0bee5781b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d3cd570-aa04-4926-b404-02474d503cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-drive-personal-info-last-name</value>
      <webElementGuid>21e4c355-a1b3-4b27-9479-ed73f928c47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.lastName</value>
      <webElementGuid>20570693-0b79-4fc4-a95c-92b5d87417a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a8a9fb6-7eae-492d-8915-5ffe32c7a33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Nachname</value>
      <webElementGuid>c232273c-8ad6-4d45-9c04-d539a0981f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss889 jss1022 MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>bcdb0e09-c4e8-4972-bb49-e503b7235f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-drive-personal-info-last-name&quot;)</value>
      <webElementGuid>e5afcb2e-f295-4136-a120-c5594612045d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='test-drive-personal-info-last-name']</value>
      <webElementGuid>5cfa9ddd-de18-4c3a-97c5-46288bb6b874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[4]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>4eec6e42-a8e8-45f9-83be-fa195b848c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>8415eb6c-0305-4287-899b-3de628bb847c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'test-drive-personal-info-last-name' and @name = 'personalInfo.lastName' and @type = 'text']</value>
      <webElementGuid>9310b9d9-7e34-465a-a2d9-de92b1a19edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
