<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vorname_personalInfo.firstName</name>
   <tag></tag>
   <elementGuidId>40da1cb1-84c6-4c4b-a4ad-c2c13a792ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='test-drive-personal-info-first-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-drive-personal-info-first-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Vorname&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b76dab8-a232-4d4b-ab33-7c7c030a6702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15bdd4e0-7754-4bdf-bb34-ce0b283dc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-drive-personal-info-first-name</value>
      <webElementGuid>e35668c7-e094-4ddf-b8ff-7000e957bf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.firstName</value>
      <webElementGuid>d460d94b-be94-46ad-8fbc-38b3bc544b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>900bee31-efc2-4272-aa9d-2dc6767f2891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Vorname</value>
      <webElementGuid>1eb2352c-367f-47c9-a437-8eb5bcef93c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss889 jss1017 MuiInputBase-inputAdornedEnd</value>
      <webElementGuid>9ae19844-ee1b-4343-93a1-c088ae4512fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-drive-personal-info-first-name&quot;)</value>
      <webElementGuid>d36ec472-d57c-49fe-8b40-e9fd53d6af5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='test-drive-personal-info-first-name']</value>
      <webElementGuid>7bc48564-1f71-4738-afbc-b1ec9a9d04e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>20867ae4-7392-4a7e-b0ee-a25e2696b67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/input</value>
      <webElementGuid>2941bbf4-1a7f-4902-8720-e0672206759f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'test-drive-personal-info-first-name' and @name = 'personalInfo.firstName' and @type = 'text']</value>
      <webElementGuid>3a355e72-bc8f-47dc-aebd-1eab33a1a9f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
