<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Nachmittag</name>
   <tag></tag>
   <elementGuidId>1b30e2af-7fb4-4660-86a9-a6bbcac97c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-']/div[3]/ul/li[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.jss760.jss1266</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nachmittag&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dfee31a7-03a2-4384-8bf8-0cf049d1c138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss760 jss1266</value>
      <webElementGuid>388e066c-e40f-4295-9a5b-37979f625959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nachmittag</value>
      <webElementGuid>e0e970fd-9aa0-440b-bcb0-ce3f0c5470aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper jss912 jss991 jss929 jss995 MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root jss930 jss996 MuiMenu-list&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss961 jss963 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-divider MuiListItem-button&quot;]/p[@class=&quot;jss760 jss1266&quot;]</value>
      <webElementGuid>acce461a-bfed-4556-9a20-baf094333c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li[2]/p</value>
      <webElementGuid>bb8fd219-8601-4088-b51f-e5fc0b144ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INEOS SPORT'])[1]/following::p[14]</value>
      <webElementGuid>2556de3c-cb27-4355-8f1f-3e7a2bc0a87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INEOS VERBRAUCHERMARKEN'])[1]/following::p[14]</value>
      <webElementGuid>4bcb4abb-11f4-438e-bf1a-5784a686aa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nachmittag']/parent::*</value>
      <webElementGuid>5c9ffee1-a8a9-4148-a690-0d85abc3a40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/p</value>
      <webElementGuid>365c86c1-59c1-4e7e-9c99-925b400ccc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Nachmittag' or . = 'Nachmittag')]</value>
      <webElementGuid>946a9ab7-2824-466f-ae52-7171f626e857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
