<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_s</name>
   <tag></tag>
   <elementGuidId>46218d6f-a2c5-4c9c-a7d7-000d5db26b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='personalInfo.yourMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;personalInfo.yourMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;s&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ce6e5eed-9793-44dd-8849-ab3e034839a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a315b51-e47b-4ca1-8f7e-068324b17dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88cb8d50-c550-4609-ad1a-46952553e36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined-error</value>
      <webElementGuid>ce61aea0-a282-4d3e-8b6c-7140229fd4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.yourMessage</value>
      <webElementGuid>9f8a65bf-5f45-44d8-b3f2-b18c8dc82c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline</value>
      <webElementGuid>031333df-b345-426e-9a72-9e5119424b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>2709bc7b-7e59-47fc-959c-e6cab9b3ed79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;jss669&quot;]/div[@class=&quot;jss840 jss841&quot;]/div[@class=&quot;jss845 jss862&quot;]/form[1]/div[5]/div[@class=&quot;jss1002&quot;]/div[@class=&quot;jss1010&quot;]/div[@class=&quot;jss1096 jss1110 jss1109 jss1114&quot;]/div[@class=&quot;jss1097&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root jss1101&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root Mui-focused Mui-focused MuiInputBase-formControl MuiInput-formControl jss1102 jss1111 MuiInputBase-multiline MuiInput-multiline&quot;]/textarea[@class=&quot;MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline&quot;]</value>
      <webElementGuid>9ff61252-ed72-410d-89e7-347af09e9598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='personalInfo.yourMessage']</value>
      <webElementGuid>80edb32f-c586-45d0-b09f-f7455e06b4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[5]/div/div[7]/div/div/div/div/textarea</value>
      <webElementGuid>e3f46b4f-19ab-4995-8314-939f729d759a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deine Mitteilung'])[1]/following::textarea[1]</value>
      <webElementGuid>6ff0f555-a060-4420-bb3d-53cf5a75082f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ja, ich möchte mehr über die Inzahlungnahme erfahren.'])[1]/following::textarea[1]</value>
      <webElementGuid>e11d5bc6-5879-4303-b242-2e0ef11a5f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per E-Mail zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>00ccaa6b-b4dc-466a-8af1-ac6f8a606967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per Mobiltelefon zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>1f11d971-b043-4317-b465-67cb1dbf3a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='s']/parent::*</value>
      <webElementGuid>f5d37971-9ac9-4e1d-8ad5-5ca94705618d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4e605811-1254-46bb-9317-5bb43060685c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'personalInfo.yourMessage' and (text() = 's' or . = 's')]</value>
      <webElementGuid>760d3e65-e4aa-4f96-8ba8-8b03b6a475b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
