<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sfsa</name>
   <tag></tag>
   <elementGuidId>c907b5ab-38e5-47cd-8271-54e901d058a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='personalInfo.yourMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;personalInfo.yourMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;sfsa&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0ae89f8d-ccdd-4ef6-9e72-80efffc65b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9dc593e-08ee-42b4-b556-6a8965f12d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>972c867d-e003-4c92-b718-4df657c6ea3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined-error</value>
      <webElementGuid>edf0f30f-2dba-4a0c-a6a4-54dac3cdbee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.yourMessage</value>
      <webElementGuid>9424f789-c127-4c6a-beb9-03cfb301bf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline</value>
      <webElementGuid>6a7937b0-cdc3-4213-badd-b007847c9b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sfsa</value>
      <webElementGuid>68bf1c26-8ce8-439a-bb9e-f23d7e47a678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;jss669&quot;]/div[@class=&quot;jss840 jss841&quot;]/div[@class=&quot;jss845 jss862&quot;]/form[1]/div[5]/div[@class=&quot;jss1002&quot;]/div[@class=&quot;jss1010&quot;]/div[@class=&quot;jss1096 jss1110 jss1109 jss1114&quot;]/div[@class=&quot;jss1097&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root jss1101&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root Mui-focused Mui-focused MuiInputBase-formControl MuiInput-formControl jss1102 jss1111 MuiInputBase-multiline MuiInput-multiline&quot;]/textarea[@class=&quot;MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline&quot;]</value>
      <webElementGuid>458f1314-2416-4276-8d32-fa4eda3cc862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='personalInfo.yourMessage']</value>
      <webElementGuid>7ab146d5-c924-4ef9-8038-c359886ada8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[5]/div/div[7]/div/div/div/div/textarea</value>
      <webElementGuid>e56dc8f8-cb46-4667-a7bb-10cac0a0d61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deine Mitteilung'])[1]/following::textarea[1]</value>
      <webElementGuid>7886c426-dc75-4b21-a1e6-463e33230758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ja, ich möchte mehr über die Inzahlungnahme erfahren.'])[1]/following::textarea[1]</value>
      <webElementGuid>ebbc7c92-6193-4c10-9173-1326e83e8f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per E-Mail zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>7de613fc-69fd-4acb-a882-42af7438b9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per Mobiltelefon zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>3a7191e9-193f-446d-a79c-0d8f4e2196c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sfsa']/parent::*</value>
      <webElementGuid>4882e649-526f-4511-a928-7ac55d97dc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>75cf92ca-ee83-44fa-9617-1ea4022740e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'personalInfo.yourMessage' and (text() = 'sfsa' or . = 'sfsa')]</value>
      <webElementGuid>b788eb8e-9b35-448b-a172-25814841c80b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
