<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sfsads</name>
   <tag></tag>
   <elementGuidId>7986d2d5-9ced-4a25-8f89-7e6e753b61e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='personalInfo.yourMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;personalInfo.yourMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;sfsads&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>84d09f42-0a22-4c2b-bb71-24d321cc46b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d9066a3f-5a4f-4d6d-8618-48176ff3c312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53557eb9-d2ce-412d-9900-31fc1e551163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined-error</value>
      <webElementGuid>810687ab-a7e4-4ca0-aa29-0aa870b3f8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.yourMessage</value>
      <webElementGuid>95ca0a94-7bfa-446a-9440-14dc6e68bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline</value>
      <webElementGuid>15f965ba-c220-49d2-8bf0-301a5288d35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sfsads</value>
      <webElementGuid>61b21a78-5eee-4e87-9be9-cc2c654d8f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;jss669&quot;]/div[@class=&quot;jss840 jss841&quot;]/div[@class=&quot;jss845 jss862&quot;]/form[1]/div[5]/div[@class=&quot;jss1002&quot;]/div[@class=&quot;jss1010&quot;]/div[@class=&quot;jss1096 jss1110 jss1109 jss1114&quot;]/div[@class=&quot;jss1097&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root jss1101&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root Mui-focused Mui-focused MuiInputBase-formControl MuiInput-formControl jss1102 jss1111 MuiInputBase-multiline MuiInput-multiline&quot;]/textarea[@class=&quot;MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline&quot;]</value>
      <webElementGuid>3b505025-39d6-4f26-94dc-61d5dd20eaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='personalInfo.yourMessage']</value>
      <webElementGuid>c91b1c61-481a-485e-8b2c-66b99ce64858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[5]/div/div[7]/div/div/div/div/textarea</value>
      <webElementGuid>40bf1da7-2418-4cb8-8a11-bdc8b7750edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deine Mitteilung'])[1]/following::textarea[1]</value>
      <webElementGuid>5dc73079-df15-4232-8c7e-0361bec9dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ja, ich möchte mehr über die Inzahlungnahme erfahren.'])[1]/following::textarea[1]</value>
      <webElementGuid>e8a372e0-3eb5-4338-927a-70de365cf589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per E-Mail zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>95738d87-48c2-4f01-a6fb-a2bf1167be42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per Mobiltelefon zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>3e535b5f-b03e-4033-abbc-7cd7f7bd9bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sfsads']/parent::*</value>
      <webElementGuid>c16f1ac1-bf42-4ddf-a904-72c816343a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ecb90220-bb2a-4714-8409-7aef14d332dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'personalInfo.yourMessage' and (text() = 'sfsads' or . = 'sfsads')]</value>
      <webElementGuid>efabadb0-0fee-40ee-98fa-000a37119f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
