<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sf</name>
   <tag></tag>
   <elementGuidId>95a15314-e3e1-4bc2-8897-8d9ce0f804f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='personalInfo.yourMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;personalInfo.yourMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;sf&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2288f0e8-a5a0-463f-8745-1d817aa329e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2047a417-6803-4ad9-a6b0-6811fdf7cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8ea24cf-ab5d-4bcd-abcf-795135aee361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>undefined-error</value>
      <webElementGuid>73dee07f-08e3-4303-8987-e16c2bdc5cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalInfo.yourMessage</value>
      <webElementGuid>eb952952-2255-4fa3-8754-c45a820aaed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline</value>
      <webElementGuid>8e00df9f-9c7b-4052-a0a4-650643a52315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sf</value>
      <webElementGuid>106c328a-2f64-4acb-8be9-143545c76c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;jss669&quot;]/div[@class=&quot;jss840 jss841&quot;]/div[@class=&quot;jss845 jss862&quot;]/form[1]/div[5]/div[@class=&quot;jss1002&quot;]/div[@class=&quot;jss1010&quot;]/div[@class=&quot;jss1096 jss1110 jss1109 jss1114&quot;]/div[@class=&quot;jss1097&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root jss1101&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root Mui-focused Mui-focused MuiInputBase-formControl MuiInput-formControl jss1102 jss1111 MuiInputBase-multiline MuiInput-multiline&quot;]/textarea[@class=&quot;MuiInputBase-input MuiInput-input jss1105 jss1113 MuiInputBase-inputMultiline MuiInput-inputMultiline&quot;]</value>
      <webElementGuid>2d6f84fe-2dee-4f1b-8aa8-bdec01fda986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='personalInfo.yourMessage']</value>
      <webElementGuid>0f85fdab-9072-4d56-977b-5a4688e0fa16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[3]/div[4]/form/div[5]/div/div[7]/div/div/div/div/textarea</value>
      <webElementGuid>8a0e5148-ec29-45ab-9add-c191ed2a6269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deine Mitteilung'])[1]/following::textarea[1]</value>
      <webElementGuid>617d2451-37eb-4988-b986-c4048e3853b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ja, ich möchte mehr über die Inzahlungnahme erfahren.'])[1]/following::textarea[1]</value>
      <webElementGuid>bdbdcc90-4c47-4f0b-b68d-c23b959ef7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per E-Mail zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>506ae121-367a-41bf-a3e1-4b9ee8f69bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ich bin damit einverstanden, Mitteilungen per Mobiltelefon zu erhalten.'])[1]/preceding::textarea[2]</value>
      <webElementGuid>350f1559-bb5b-4d2e-9a6a-08fd5374bcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sf']/parent::*</value>
      <webElementGuid>3986b4e4-bdee-4dbf-8fb0-50006f9d0d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e1c1811e-bbd5-4d3b-8aba-8392604d4255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'personalInfo.yourMessage' and (text() = 'sf' or . = 'sf')]</value>
      <webElementGuid>cb22faef-b475-41bb-a511-553f2debddc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
