<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan Tenure_loanterm</name>
   <tag></tag>
   <elementGuidId>c59fc819-16a2-4f70-bd14-b7765e53dd2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loanterm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loanterm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Loan Tenure&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4a6313c-c3a3-41b3-9e9c-ee9b1f10c62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a5bba1e6-c784-403d-8936-b10c2d500317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loanterm</value>
      <webElementGuid>53ccb4d7-7c31-444b-8c47-925189ae918d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loanterm</value>
      <webElementGuid>10ea29f9-ede9-48be-9c64-bb710d575a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7932cd84-1ab4-49e6-83f6-0a25c0a32a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5322c6f1-c1ee-4247-98ce-2c5e4c6b8512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loanterm&quot;)</value>
      <webElementGuid>5b2adab4-0c1d-44e8-9a0b-fcc092951da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loanterm']</value>
      <webElementGuid>5014e89d-359f-4ceb-bbc9-0b1e00fc1d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='emicalculatorinnerform']/div/div/div/div/input</value>
      <webElementGuid>524e93dc-daa8-4b17-b14f-d7d7aebf5438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>e1c5fb6a-7548-4975-8c6b-a3be9195f299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
