<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Track order_close-icon</name>
   <tag></tag>
   <elementGuidId>61730e45-adea-4e9a-9d89-84d4d5b679eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a056c1c-660a-4e61-9a16-b85f7ae4aada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b972fad-c411-4d6f-b62e-39fc82f362ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>f8d601f4-5bf5-454d-b20c-a9c6d35e0d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;modal-dialog loginmodalcenter registermodalcenter&quot;]/div[@class=&quot;modal-content&quot;]/button[@class=&quot;close titan-login-modal-close close-modal&quot;]/span[@class=&quot;close-icon&quot;]</value>
      <webElementGuid>791d97b1-56dc-4948-8cb5-721de2c08b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div/div/button[2]/span</value>
      <webElementGuid>48821560-1895-43a1-8076-4fb64099aa93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>efa45eef-bb10-4cf5-b149-78087b0b2840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
