<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cmm-cookie-banner_Skip to content ((Main Na_449722</name>
   <tag></tag>
   <elementGuidId>04a1e622-1847-4672-bb18-f9720549765d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//cmm-cookie-banner</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>cmm-cookie-banner.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>cmm-cookie-banner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cmm-cookie-banner</value>
      <webElementGuid>b40fc3e7-8035-422d-bacd-64108eeead04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>settings-id</name>
      <type>Main</type>
      <value>k-l7rZd3t</value>
      <webElementGuid>62848ee0-4916-4c39-8395-9ada70cc153f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>e203c396-1af1-47a2-8bdb-1774abf4f9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>de</value>
      <webElementGuid>50fcdfdf-9b05-4f9e-a190-5a34249e104a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-market</name>
      <type>Main</type>
      <value>AT</value>
      <webElementGuid>cc398de2-a2a2-479d-b7cf-72b439c8a940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>35742b4b-0905-4aa3-bf7a-d980c209f275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;generic-template generic,page,basicpage&quot;]/cmm-cookie-banner[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>4cae8cc1-931f-4abc-aa62-5b0582ece868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cmm-cookie-banner</value>
      <webElementGuid>22a06af2-4d29-4c39-9a59-8ff2dc9f0bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
