<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email</name>
   <tag></tag>
   <elementGuidId>40687c1b-87ef-4c55-a4be-85893ffecb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@name='Email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Email' or . = 'Email')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sectionContent-283</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67a49443-1868-4cae-b54f-5ab4f8521ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>test-id__section-content slds-section__content section__content align-with-title</value>
      <webElementGuid>59fdbfff-f74c-4093-a159-79bf99b89dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sectionContent-283</value>
      <webElementGuid>d38c43ea-75d5-4617-a441-f87fdc507c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ee47d06-7f36-4519-9abf-f0fd1fe4bb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>1a2a2e4c-87c1-4e03-8455-2d06ed8344d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionContent-283&quot;)</value>
      <webElementGuid>5e506d89-0ac1-42fb-a965-fa3599edc2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Information'])[1]/following::div[1]</value>
      <webElementGuid>438bd8e7-e726-4267-86b8-5e4bb573b16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verified Help Info'])[1]/following::div[3]</value>
      <webElementGuid>eed64bc2-8c29-49b9-86e8-7b0a2c16f081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sectionContent-283' and (text() = '*EmailPhoneOther EmailMobileAddressStreetCityState/ProvinceZip/Postal CodeCountryNon-Responsive Follow-upNon-Responsive Follow-up Help InfoThe number of times that Salesforce sends follow up email to the Lead when he/she becomes dormant for a pre-set period of time.--None--' or . = '*EmailPhoneOther EmailMobileAddressStreetCityState/ProvinceZip/Postal CodeCountryNon-Responsive Follow-upNon-Responsive Follow-up Help InfoThe number of times that Salesforce sends follow up email to the Lead when he/she becomes dormant for a pre-set period of time.--None--')]</value>
      <webElementGuid>4a9c0b99-3324-43ca-b099-1cf35197db6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_1561:0']/div/div/div/records-modal-lwc-detail-panel-wrapper/records-record-layout-event-broker/slot/records-lwc-detail-panel/records-base-record-form/div/div/div/div/records-lwc-record-layout/forcegenerated-detailpanel_lead___012000000000000aaa___full___create___recordlayout2/records-record-layout-block/slot/records-record-layout-section[2]/div/div</value>
      <webElementGuid>7cd073a4-e3d0-4f2a-999c-6af78511b4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-283']</value>
      <webElementGuid>6917ce17-658b-48a8-9af0-ec4755f040b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-section[2]/div/div</value>
      <webElementGuid>af65d702-dc18-4f3e-bbb3-f61cdccf2956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
