<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_firstName</name>
   <tag></tag>
   <elementGuidId>eae141ec-a954-4945-924c-1c518b325b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@type = 'text' and @placeholder = 'First Name' and @name = 'firstName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'First Name' and @name = 'firstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-169</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aba4c56a-0d37-42b4-81cb-1d3e0a65e9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>45db9068-ea71-456b-8945-36e5adcbab3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>704116f5-7e1c-424f-8685-e291cf60f5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-169</value>
      <webElementGuid>3581900c-ddf3-424c-911f-bfa6aed94a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ffc80e40-a8d4-427a-8683-77ef8bb9d421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>4c365057-f5de-4309-b1b7-de39bb8b6b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>e56a15eb-0c0d-4035-83d9-d6c81056eeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-169&quot;)</value>
      <webElementGuid>e3e7f3b9-ced7-4e2a-a550-8845ea2f22ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-169' and @placeholder = 'First Name' and @name = 'firstName']</value>
      <webElementGuid>90dc4b17-323a-4464-ab79-b3fa064fefe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-159']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-input-name/lightning-input-name/fieldset/div/div/div[2]/lightning-input/div/input</value>
      <webElementGuid>2b7b955e-46f5-44c5-bb62-29b2a1af44ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-169']</value>
      <webElementGuid>8ddb7e2b-f8c8-4f3b-ab6d-adc001e86cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/div/input</value>
      <webElementGuid>39b0d0a1-e3cf-43ea-9e71-0cd32db3fd62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
