<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Available for CHENNAI, India 600119</name>
   <tag></tag>
   <elementGuidId>955d6ad8-adc9-4efb-84ac-827f3f024aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.delivery-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div[2]/div[2]/div/div/div[3]/div/div/div/div[2]/div[6]/div[3]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Available for CHENNAI, India 600119&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9833eb13-4431-412d-a653-0d1845e9940c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delivery-message</value>
      <webElementGuid>8d0345c1-8651-4eac-bc30-aee37063eb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Available for CHENNAI, India 600119</value>
      <webElementGuid>05ee298c-89bd-4f01-b915-821da8a4d2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;pdp-global-container tw-raga&quot;]/div[@class=&quot;product-wrapper-raga-nebula&quot;]/div[@class=&quot;container product-detail product-wrapper tw-pdp-raga&quot;]/div[@class=&quot;row justify-content-end no-gutters&quot;]/div[@class=&quot;col-12 col-lg-5 col-md-6 product-details-section tw-pdp-raga&quot;]/div[@class=&quot;product-details-container&quot;]/div[@class=&quot;h-limit&quot;]/div[@class=&quot;inner-h-limit&quot;]/div[@class=&quot;attributes w-100&quot;]/div[@class=&quot;delivery-check&quot;]/div[@class=&quot;delivery-check-error delivery-msg serviceability-details&quot;]/div[@class=&quot;success-deliverable&quot;]/div[@class=&quot;delivery-message&quot;]</value>
      <webElementGuid>0c0a73e3-a7bc-4041-a7fb-1e03ab85f260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div[2]/div[2]/div/div/div[3]/div/div/div/div[2]/div[6]/div[3]/div[2]/div</value>
      <webElementGuid>05d10bd0-5e7e-43e1-bad3-19d5b747dbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispatch By 23rd Apr 2024'])[1]/following::div[2]</value>
      <webElementGuid>192b97e0-7452-4fe2-9bb6-eb7aeabd98bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check'])[1]/following::div[4]</value>
      <webElementGuid>9bd0faed-20b7-4e41-9fdd-79653b2d7921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Express Delivery by'])[1]/preceding::div[7]</value>
      <webElementGuid>9ebe8aa3-8106-41f2-939f-7445bb4ed847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thursday, 25th April'])[1]/preceding::div[8]</value>
      <webElementGuid>0c32c787-5318-4471-a49d-d59f08a8db56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Available for CHENNAI, India 600119']/parent::*</value>
      <webElementGuid>67dc25df-a7c3-40a2-b975-88db6dac419f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div[2]/div</value>
      <webElementGuid>1916cf04-6133-4050-990f-d1ce6dccf4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Available for CHENNAI, India 600119' or . = 'Available for CHENNAI, India 600119')]</value>
      <webElementGuid>ae6719b7-200a-47b4-b206-8c0fe8e1358a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
