<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your work</name>
   <tag></tag>
   <elementGuidId>5a7b57f0-5cb5-4991-9b9e-ec1740fa424b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/div/div/div/div/div/nav/div/div/a[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-1d00n3d > div.css-1vg8prp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Your work&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>003daa02-3937-4c90-86ba-aeb727064898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1vg8prp</value>
      <webElementGuid>802ec21b-3030-4646-8968-02a5297a2423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your work</value>
      <webElementGuid>53c647b1-a6ad-4031-9661-8ad812112bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;css-e69dqy&quot;]/div[@class=&quot;css-e69dqy&quot;]/div[@class=&quot;css-e5j86h&quot;]/div[@class=&quot;css-1c9jniz&quot;]/div[1]/div[@class=&quot;css-ptltcw&quot;]/nav[@class=&quot;css-1mk959p&quot;]/div[@class=&quot;css-1w0k1li&quot;]/div[1]/a[@class=&quot;css-1d00n3d&quot;]/div[@class=&quot;css-1vg8prp&quot;]</value>
      <webElementGuid>792cef23-cce2-4537-a30e-8dab77678352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div/div/nav/div/div/a[2]/div</value>
      <webElementGuid>7d8e9976-f542-46c3-b657-d4ae9d3a59e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask or search'])[1]/following::div[1]</value>
      <webElementGuid>18de1ba5-1baf-4721-9dec-dff1f08004c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[2]</value>
      <webElementGuid>6d785f3d-abca-4827-b075-afbfb5d17f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/preceding::div[1]</value>
      <webElementGuid>a6e53f4d-8b90-4e4a-a607-d1e5807d098b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::div[2]</value>
      <webElementGuid>62a0e433-78da-492a-ae68-f44f046c24a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your work']/parent::*</value>
      <webElementGuid>835c8152-6305-42ad-b010-a6990259b22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div</value>
      <webElementGuid>42a00211-1055-47d5-af50-da362fdf97e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
