<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_seconds_button1</name>
   <tag></tag>
   <elementGuidId>107c7dca-5426-4d78-a3d6-f9933a40c3c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_otp > div.buttonWrapper > input.button1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Verify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Verify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5e3d094-e5ed-408a-b4e8-7aa070eaf539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2508d0b4-a3fb-4cc0-9928-91dc5b86c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>7b2c1e7e-35c2-42c5-b0cb-80771d3ad5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button1</value>
      <webElementGuid>be203192-dcb4-4139-aac8-05c5c1eb72a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>form_otp_submit()</value>
      <webElementGuid>2bdbe0c0-503f-4ed0-a658-581ebfeab622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_otp&quot;)/div[@class=&quot;buttonWrapper&quot;]/input[@class=&quot;button1&quot;]</value>
      <webElementGuid>b173699b-92bb-4481-b5e2-5bc9036319fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Verify']</value>
      <webElementGuid>84b4d9b4-5be6-412e-9a86-5f965e226f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_otp']/div[4]/input</value>
      <webElementGuid>537936cd-93fb-40b7-aaad-f2420c8bfad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5fcc1cac-a3f8-41c9-8033-8b8cc8b5dec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
