<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PAN NUMBER_pan</name>
   <tag></tag>
   <elementGuidId>d7edf6e4-2178-4c28-a949-966efb46e52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61321f43-d8a1-4b16-83e2-a8f8ffb33d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb745686-467f-4a6f-ac69-102d453fff5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pan</value>
      <webElementGuid>c0201057-edc7-4e76-a4ca-fd2de098cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pan</value>
      <webElementGuid>77f90289-5075-48bc-bc83-ea39b32419f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pan&quot;)</value>
      <webElementGuid>f2a949c7-1944-4fe2-a443-11a172a23eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pan']</value>
      <webElementGuid>31b08d25-16ca-4a13-ade5-8b9875a86f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_pan']/div/div/input</value>
      <webElementGuid>dc04b668-94ea-4c7f-8c78-309abaaaa588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c58be36d-df3d-472d-a811-d2fc721e51f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
