<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Father Name_father_name</name>
   <tag></tag>
   <elementGuidId>dfec347d-12d8-4fbc-a1ac-93d54587583b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#father_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='father_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#father_name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45426dbd-57c5-4bd5-9b96-5e969f5b2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b71b1b64-f9eb-4b1f-b484-e1db0c391482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>father_name</value>
      <webElementGuid>2cb005bb-5b7e-49a6-b6aa-0854adffc2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>father_name</value>
      <webElementGuid>59b7e488-4ab6-44df-8bd8-abe1fd51c493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;father_name&quot;)</value>
      <webElementGuid>8d02000b-655c-4abf-aae9-12a41d70987a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='father_name']</value>
      <webElementGuid>f593a5e3-96cc-4bd6-907f-7e9aeb613503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_mobile']/div[2]/div/input</value>
      <webElementGuid>0cb46756-6714-4853-963a-18d69ee3ade7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0a40c059-7a50-445c-94e3-d88a4b8b141f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
