<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_CAPTCHA</name>
   <tag></tag>
   <elementGuidId>0a9bc423-8c14-4ce4-adcf-460c0bcdcf42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@title = 'reCAPTCHA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-8g0kpq470trq&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-flexbox-02']/div/fieldset[5]/div/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-8g0kpq470trq&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27d22f03-9d12-4b25-a6b2-896abb2b46c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>1a31aadc-34b0-420a-8aa4-4764717957d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>8a955455-2d56-4969-8070-e54c5fa0715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>04439706-6848-4c5f-87ce-3fcf1ee8585e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1e2bad22-8c5a-4866-b39c-85e9d455d113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-8g0kpq470trq</value>
      <webElementGuid>c32441f2-0270-4d4c-b45f-5011dbe9de2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>701cac65-5a10-476e-aaae-24427233b411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>97861c68-5dad-43d8-a850-6516377a3847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>61baac81-4e4a-49d2-a7f3-703d08d16a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcUhRQUAAAAAL0OugF7_KbILj09JPz5LYlz8zsP&amp;co=aHR0cHM6Ly93d3cucHVyaW5hLmRlOjQ0Mw..&amp;hl=de&amp;type=image&amp;v=aR-zv8WjtWx4lAw-tRCA-zca&amp;theme=light&amp;size=normal&amp;cb=gsvh6h2z2wx2</value>
      <webElementGuid>91bc0af5-df9b-4f90-8c42-93184daff604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-flexbox-02&quot;)/div[@class=&quot;fieldset-wrapper&quot;]/fieldset[@class=&quot;captcha captcha-type-challenge--recaptcha&quot;]/div[@class=&quot;captcha__element&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>2342dd23-9c38-409e-ba56-f061d6ca5b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-flexbox-02']/div/fieldset[5]/div/div/div/div/iframe</value>
      <webElementGuid>bb84f0df-79b9-4f15-8dc3-bef6f98098b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-8g0kpq470trq']</value>
      <webElementGuid>47d99c4b-995d-4d05-b9b3-a88681fd8dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/iframe</value>
      <webElementGuid>bc4e79b8-f159-4952-9c4c-bfacc5e416ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
