<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nachname_lastname</name>
   <tag></tag>
   <elementGuidId>d15c26ce-9e10-4624-88b0-2f66e65e17b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-flexbox']/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nachname&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8925349b-f3ec-425f-8d95-2acd41056645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-required-error</name>
      <type>Main</type>
      <value>Dies ist ein Pflichtfeld.</value>
      <webElementGuid>44b946b5-998b-40c1-87c3-da9abac26784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^!@#$%&amp;*()/>&lt;\][\\\x22,;|]+</value>
      <webElementGuid>62159e32-1e6c-49e9-8e49-6ee54f568ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-pattern-error</name>
      <type>Main</type>
      <value>Bitte gib gültige Werte ein</value>
      <webElementGuid>92ddef26-2dd8-40c2-9618-6a95a06cb079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-lastname</value>
      <webElementGuid>a7099422-238e-4185-a9f2-1ec7d88f5a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-maxlength</name>
      <type>Main</type>
      <value>Nachname field has a maximum length of 255.</value>
      <webElementGuid>9d21c0da-4d88-43f0-a16b-2c8e1a1a707f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Dies ist ein Pflichtfeld.</value>
      <webElementGuid>0fa5a974-037c-492f-b57a-d8bad7721a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-pattern</name>
      <type>Main</type>
      <value>Bitte gib gültige Werte ein</value>
      <webElementGuid>7d986f53-1573-464c-88bd-6359b2783872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>067b0117-928c-43a4-b182-5534a25caa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-lastname</value>
      <webElementGuid>b205ddff-cefb-4c7d-b50f-229224e44749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>b5c90d2c-1cd3-4fae-89aa-7e9f3e8bfbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b0e87b2e-3d41-4689-9701-03641948c332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6e400c55-f6fd-400b-89b9-9681f30e7c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text required</value>
      <webElementGuid>6f1fbc5d-6370-4c69-9a1d-893b6ede76e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>caaf6f81-fae9-4a40-8624-d03bca0c1d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2a13b4a-8ca2-4d17-8764-9d7861b1ad2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-required-error</value>
      <webElementGuid>55cbf9de-8624-4ec1-a733-984780cb733c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-lastname&quot;)</value>
      <webElementGuid>c5ad565e-f568-4312-9acf-acc755844eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-flexbox']/div[2]/div/input</value>
      <webElementGuid>5b3e4024-48de-45ba-844c-73c80ec747c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-lastname']</value>
      <webElementGuid>a3da561a-274b-457f-bd7f-f81f2ae71965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/input</value>
      <webElementGuid>309e4278-4ff5-476b-b5f6-ee58e9dd9194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
