<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_consent_three_consent_three</name>
   <tag></tag>
   <elementGuidId>923b79f5-6aad-4b94-aba0-1d78e5f44b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-consent-three</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-flexbox-02']/div/div[8]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;consent_three&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bf6e8a6-726a-46ab-a835-496c1741a354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-consent-three</value>
      <webElementGuid>e139bdae-e4ba-482d-bcc6-188c904d36ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>edit-consent-three--description</value>
      <webElementGuid>fb972fe7-ae42-4e7f-a7b0-f666189433a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de0208d5-dc34-4d8c-acb4-92c27efaed97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-consent-three</value>
      <webElementGuid>7b499653-8159-4d79-9884-233a0ce311a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>consent_three</value>
      <webElementGuid>53c84513-516a-4238-9df5-6442ffd7d1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3328bbfc-8762-43c2-b602-c6250a31fc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox</value>
      <webElementGuid>3379e8d8-8f92-4428-98f9-47c29e3b68b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-states</name>
      <type>Main</type>
      <value>{&quot;disabled&quot;:{&quot;.webform-submission-newsletter-paragraph-45588-add-form :input[name=\u0022consent_d\u0022]&quot;:{&quot;unchecked&quot;:true}}}</value>
      <webElementGuid>a36088c8-741b-4f79-83dd-9f74b984c58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-consent-three&quot;)</value>
      <webElementGuid>3f87a6c1-8e0b-46f2-8dd6-850f24773721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-flexbox-02']/div/div[8]/div/input</value>
      <webElementGuid>1168a6a3-2a06-4402-b78d-99d266c5fdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-consent-three']</value>
      <webElementGuid>226f883a-8d24-4b99-a3e4-78fa871a6ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>04b695ee-a93a-4002-ac34-7ee50b883e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
