<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name deines Haustiers_pet_name</name>
   <tag></tag>
   <elementGuidId>0cedaed0-338b-4886-92b8-28feae283dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-flexbox-01']/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-pet-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Name deines Haustiers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1af683d3-06e8-45b6-9183-255b57bc1ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[^!@#$%&amp;*()/>&lt;\][\\\x22,;|]+</value>
      <webElementGuid>6c0c5fc5-117f-4717-bc85-0e6f14d42725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-pattern-error</name>
      <type>Main</type>
      <value>Bitte gib gültige Werte ein</value>
      <webElementGuid>c9b34fb9-a3be-4a7b-adc4-b94e54a36232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-pet-name</value>
      <webElementGuid>23b05ce6-9cf3-4f70-a3e2-d35aafe5a57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-maxlength</name>
      <type>Main</type>
      <value>Name deines Haustiers field has a maximum length of 255.</value>
      <webElementGuid>ca31e175-398b-4697-b8b9-08f6ca62fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-pattern</name>
      <type>Main</type>
      <value>Bitte gib gültige Werte ein</value>
      <webElementGuid>b406a9b6-b4ce-4397-9957-cbdb35fdf291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1fb4023-0293-4d36-aeda-6dd895bb2363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-pet-name</value>
      <webElementGuid>0c6b52d6-7dca-4bc8-b3d4-47d6d5676c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pet_name</value>
      <webElementGuid>5ef7d90b-bc7e-4d2e-9e5f-498bdb72c5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>fd475fe6-f91a-4639-9075-6804436f52ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>167f7af5-eb61-4c1a-9445-ea3e470ab572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text</value>
      <webElementGuid>065c32d3-0543-40e6-b45c-683371ae4331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-required-error</value>
      <webElementGuid>9d5daa03-dbc4-46ca-b284-b5c21e4c3865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-pet-name&quot;)</value>
      <webElementGuid>c9239813-14c7-4525-8b8f-d20fbfa2cd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-flexbox-01']/div/div/input</value>
      <webElementGuid>45eab0d4-8c48-4fa5-b30c-d7a92df43822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-pet-name']</value>
      <webElementGuid>83c3a472-c273-4554-b64c-069db5296cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>0ea12887-5e4a-4ea7-b2f9-e57b0830bf79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
