<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_PURINA ONE</name>
   <tag></tag>
   <elementGuidId>7cdae9fb-0242-461c-99ad-1d7a0dab17f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image-label--purina_one_cat.js-form-item.form-item.js-form-type-checkbox.form-type-checkbox.js-form-item-cat-brand-purina-one-cat.form-item-cat-brand-purina-one-cat > label.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-cat-brand']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit-cat-brand >> internal:text=&quot;PURINA ONE&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c7e21f1a-305f-4496-9b5b-229cf445779d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>edit-cat-brand-purina-one-cat</value>
      <webElementGuid>53c10ba4-e1d4-4bfe-8b8c-e5228ae2362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cbcf2ef2-98e5-477f-a30e-460e9efd40d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PURINA ONE</value>
      <webElementGuid>1786afcb-fe79-4780-ad48-b6f275f7d54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-cat-brand&quot;)/div[@class=&quot;image-label--purina_one_cat js-form-item form-item js-form-type-checkbox form-type-checkbox js-form-item-cat-brand-purina-one-cat form-item-cat-brand-purina-one-cat&quot;]/label[@class=&quot;option&quot;]</value>
      <webElementGuid>ed9c90b5-b01f-468b-8f6d-3d781589c755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-cat-brand']/div/label</value>
      <webElementGuid>cb56f834-cf05-460b-97ee-9946d4f2f759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsere Katzenmarken'])[1]/following::label[1]</value>
      <webElementGuid>cd085554-e0d8-4ab5-8267-efe265323947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geburtstag deines Haustiers'])[1]/following::label[1]</value>
      <webElementGuid>b655011f-58c6-4013-a6d4-daeb253c3e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOURMET'])[3]/preceding::label[1]</value>
      <webElementGuid>2b5379c7-05ee-4921-bf0c-ed4a905b60b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FELIX'])[3]/preceding::label[2]</value>
      <webElementGuid>8e1f31a8-11a1-4311-9c6a-72aaac4577b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/label</value>
      <webElementGuid>fa9e358a-7773-4c73-8d3b-48e552063e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
