<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop by Collection</name>
   <tag></tag>
   <elementGuidId>2c3554c3-dc0d-4f24-8855-84afbc39e99e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shop-by-collections-men</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='shop-by-collections-men']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;watches-for-men&quot;i >> #shop-by-collections-men</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db2da896-ecb5-4fa6-b9e7-009a5f663bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.titan.co.in/shop/watches-for-men?lang=en_IN</value>
      <webElementGuid>854e5f06-d0f3-4355-bdaa-776b98514ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shop-by-collections-men</value>
      <webElementGuid>63d7fdf4-464b-4f2e-8a54-122473918bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>7b6248f6-f440-45d6-ac3f-96930157ae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-link menu p-0 column-header-font-2 column-header-color-2 </value>
      <webElementGuid>fa72f542-c044-454d-8d57-d86eda0e0bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e789916-ead9-4bb6-be88-4a93036bfdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Shop by Collection
</value>
      <webElementGuid>e7c60b17-3478-4701-8c1b-ce80298f4fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page&quot;]/div[@id=&quot;sg-navbar-collapse&quot;]/nav[@class=&quot;navbar navbar-expand-lg bg-inverse col-12 nav-bar-mobile&quot;]/div[@class=&quot;menu-group d-none d-xl-block headings px-1 js-mega-nav&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav navbar-nav nav-item header-menu-ul m-0&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/div[@class=&quot;dropdown-menu show&quot;]/ul[1]/div[@class=&quot;align-items-baseline category-menu-item&quot;]/li[@class=&quot;dropdown-item dropdown mega-menu-l2 py-c-1 d-flex&quot;]/a[@id=&quot;shop-by-collections-men&quot;]</value>
      <webElementGuid>6ea5450b-51b6-4093-9db3-164c82ea4a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='shop-by-collections-men']</value>
      <webElementGuid>330b5e0b-9c50-401e-a074-ed91c771c867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-navbar-collapse']/nav/div[2]/div/ul/li/div/ul/div/li[8]/a</value>
      <webElementGuid>0acfc574-d209-4dbf-9b7b-19814a0c7e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shop by Collection')]</value>
      <webElementGuid>acdc9c3d-8e77-49b9-a42b-969a42893a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lee Cooper'])[1]/following::a[1]</value>
      <webElementGuid>e3f47f8c-dd00-4554-9fe5-9ed671011020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerruti'])[1]/following::a[2]</value>
      <webElementGuid>ffd0697f-d699-4be5-a23d-9692cbd6a838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by Collection'])[2]/preceding::a[1]</value>
      <webElementGuid>36650427-04dc-45dc-88de-9b3ce520feba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grandmaster'])[1]/preceding::a[1]</value>
      <webElementGuid>cd95020f-4221-456c-9068-90eb24226ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shop by Collection']/parent::*</value>
      <webElementGuid>4f1ab372-abb0-4de9-a7e9-c1cbc438b9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.titan.co.in/shop/watches-for-men?lang=en_IN')])[5]</value>
      <webElementGuid>b469f14f-7039-483a-9616-572a1d496874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[8]/a</value>
      <webElementGuid>dc73f0a4-c496-4b0d-82da-b1d0d7fc4351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.titan.co.in/shop/watches-for-men?lang=en_IN' and @id = 'shop-by-collections-men' and (text() = '
Shop by Collection
' or . = '
Shop by Collection
')]</value>
      <webElementGuid>de257ccf-a6ab-4ac3-bed6-5b562dd5d550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
