<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>aa5380be-892c-4604-a37d-8a597ebe1cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral.search-button.slds-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Manager'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c1e4348-1344-4e70-8191-e6065ad1750e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8952fdb9-5f87-44e6-baa6-f1a5603196b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral search-button slds-truncate</value>
      <webElementGuid>3b7ef6b9-9a1d-4582-9822-0cc53d251308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8a7476a4-2684-4dbb-81f6-df1f167b928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>115:0;p</value>
      <webElementGuid>d3e287cc-3ebf-4324-a08e-0bacc959360f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>f51249fc-4e68-4c4e-8035-9eb1a389f213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneHeader&quot;)/div[@class=&quot;slds-global-header slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;slds-global-header__item slds-global-header__item--search&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 slds-grid--align-center forceSearchAssistant&quot;]/button[@class=&quot;slds-button slds-button_neutral search-button slds-truncate&quot;]</value>
      <webElementGuid>cc52e0a2-d1b3-4c31-a72b-1368b7338d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Manager'])[1]/following::button[1]</value>
      <webElementGuid>546abe0d-e313-4e5d-8eb4-921e792a2e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>1acbb839-d394-4327-8615-f7b8926dc6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Manager'])[2]/preceding::button[1]</value>
      <webElementGuid>59c583dc-a172-43bc-b780-06f9641e001e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add favorite'])[1]/preceding::button[1]</value>
      <webElementGuid>2bdd7f50-a9c5-4ce4-aa8d-006f179f543f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search...']/parent::*</value>
      <webElementGuid>feb10dbe-f38a-4f2f-8120-9881e7297126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>1372ed80-9374-485b-b6b6-e6d62eb0f943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='oneHeader']/div[2]/div[2]/div/button</value>
      <webElementGuid>07b5b6a1-c9a5-463c-a504-2994961ab088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f2a67033-c7ea-45ee-aa09-114c931abd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @class = 'slds-button slds-button_neutral search-button slds-truncate' and (text() = 'Search...' or . = 'Search...')]</value>
      <webElementGuid>4b658c75-6682-4ccc-926f-5996a95097b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
