<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mohit Kuma_icon</name>
   <tag></tag>
   <elementGuidId>1ff0c7b3-e213-4777-ba43-08263b524044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//div[contains(@title, '${username}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2b24bd81-cfae-478c-a6a5-31c759c48e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>6:2347;a</value>
      <webElementGuid>3ad9bade-1828-41c6-aa05-4e20b29a1cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png</value>
      <webElementGuid>0b8c20a2-f480-45f6-aa93-0c825e551e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon </value>
      <webElementGuid>7d0bf5b5-e652-421e-adf8-82b4548591b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>e6dcc80d-c42f-44d7-b6f9-9a35d335e6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>5a007dcf-0712-45be-a29a-e6b7d2aba1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1:2347;a&quot;)/div[@class=&quot;mruIcon slds-icon slds-icon--small slds-float--left slds-m-vertical--xx-small slds-m-left--xx-small slds-media__figure forceEntityIcon&quot;]/span[@class=&quot;uiImage&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>f6bcee89-15a2-45d2-8052-f3b2b42b7dea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1:2347;a']/div/span/img</value>
      <webElementGuid>585be797-3b53-42a5-944a-8416e41e43f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='User'])[3]</value>
      <webElementGuid>7bdf99c3-a242-4c73-859a-fc91e7d27fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span/img</value>
      <webElementGuid>9192e6ed-1479-47e8-b0f1-c7086f134368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon-inc--demo.sandbox.my.salesforce.com/img/icon/t4v35/standard/user_120.png' and @class = 'icon ' and @alt = 'User' and @title = 'User']</value>
      <webElementGuid>920f4ae6-4ac0-4e11-b122-8e089d04ed7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
