<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1</name>
   <tag></tag>
   <elementGuidId>7cd79254-cd32-4c14-9fe9-45f1c4afb5b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-semantics-role = 'text-field' and @aria-label = 'Amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flt-semantic-node-19 > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-19']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Amount&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7263eb93-3756-4bf5-94f1-e180be3ecaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5dea7f68-199c-4c9e-9928-ef5fd5c7166c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>00f108b9-5be7-4f24-b843-14307ce6b8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5fc4c027-ec6b-4303-b652-3c5688e2c1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-semantics-role</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>98e2e0de-f1fa-4b95-a4bb-715769a1f08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>8956f4c3-98f1-4b39-9dd8-27cf0025b7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-semantic-node-19&quot;)/input[1]</value>
      <webElementGuid>06b25e99-12a5-4cbc-b43d-af0d7bfa343b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-19']/input</value>
      <webElementGuid>8b99d81b-362a-4bd7-8555-fc9ffd1b7c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-semantics[2]/input</value>
      <webElementGuid>e556083b-d92c-4053-abab-5419acdc751b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@data-semantics-role = 'text-field' and @aria-label = 'Amount']</value>
      <webElementGuid>3a0010f0-73b6-4dac-84f9-3f60927a2025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@aria-label = 'Amount']</value>
      <webElementGuid>0e9f875d-c891-4508-b954-127fda9568b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
