<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search this list_Contact-search-input</name>
   <tag></tag>
   <elementGuidId>b432ad33-9318-4e96-9b0d-033c82ddfca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Contact-search-input' and @placeholder = 'Search this list...' and @type = 'search']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_1']/div/div/div/div/div/div[2]/div[2]/force-list-view-manager-search-bar/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-203</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search this list...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>371ee924-643b-4818-8ef8-ff4994d96b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>156a3995-cbde-4212-9e03-014633da411d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-203</value>
      <webElementGuid>53fde6a6-70b1-4d7b-b30a-8c04162bbeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Recently Viewed list view.</value>
      <webElementGuid>43166276-f542-4d0f-8a57-e9e61115326c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-203</value>
      <webElementGuid>983be9d4-13d3-47ac-a8ee-e1a987053373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Contact-search-input</value>
      <webElementGuid>0859c6a2-2d9d-456f-96e7-87989eb572b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d04bb18-8f5b-481f-945d-c12d7d19c484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>5fbfd368-7f4a-47ab-8251-7b5e03f8b078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>094e4db8-5724-45aa-ab86-b97bc4a4881d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>listviewSearchTooltip-192</value>
      <webElementGuid>39a9885e-e695-4799-aa95-680a79041bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-203&quot;)</value>
      <webElementGuid>486635bd-420f-411d-b3ed-cfe01c3c6c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-203']</value>
      <webElementGuid>c355d8b2-6924-4860-b499-3c1413a419ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/div/div[2]/div[2]/force-list-view-manager-search-bar/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>b2eb7b77-c970-4b44-86ed-2ad8fc56cbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>7ea21ed1-c212-420a-a4b6-d133ea6be90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-203' and @name = 'Contact-search-input' and @placeholder = 'Search this list...' and @type = 'search']</value>
      <webElementGuid>b65caea2-20f5-47a5-9fd8-09dff85503b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
