<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar</name>
   <tag></tag>
   <elementGuidId>04c80aaa-913b-40ca-bfd2-88266dcff96c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>kendo-calendar[id^='kendo-calendarid-']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
