<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Today</name>
   <tag></tag>
   <elementGuidId>ff4849f1-37a4-4c1b-af1d-a78d135e4dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[ng-reflect-ng-class=&quot;k-today&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
