<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_closeButton</name>
   <tag></tag>
   <elementGuidId>1c62636e-7ef8-496a-b016-f9244aa0aa72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closeButton</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'closeButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5f16cc9-4d39-4bb7-a852-527150a76773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-button</value>
      <webElementGuid>9570a82c-ea0f-461d-b447-d84daf61e623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeButton</value>
      <webElementGuid>743b6ded-af67-4ae4-b4f6-066e79fafa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>3c06fe5f-fc23-4030-bcd1-c3af6103013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeButton&quot;)</value>
      <webElementGuid>9b6ca768-5b5b-4046-abda-aa13329ff577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup']/span</value>
      <webElementGuid>a701e5bd-229e-4156-bc4b-6861b3cd34b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='closeButton']</value>
      <webElementGuid>4be817a7-6ebe-4d80-8ad7-9be57832b891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie-Einstellungen'])[1]/following::span[1]</value>
      <webElementGuid>fd5310db-e4d3-4d26-ae09-065bda587904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melde dich zu unserem Nestlé Newsletter an.'])[1]/preceding::span[1]</value>
      <webElementGuid>fa623ff9-025d-4f62-99ef-e3e27adb73f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>f4c77477-dd51-4cb6-b3db-b3dcfb7b674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/span</value>
      <webElementGuid>2342694d-deca-454b-8df9-9aa99b2a8231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
