<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SDK Form plugins</name>
   <tag></tag>
   <elementGuidId>a1890690-a8ea-45cc-84e6-eee4bce01e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tab-1&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/p[@class=&quot;multiple&quot;]/a[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SDK: Form plugins')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SDK: Form plugins&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0561646-04de-47e3-b375-a1965d24c8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://help.nintex.com/en-US/formplugins</value>
      <webElementGuid>b50e20bd-3af0-41a3-8366-7188003b35db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>07fcf136-d459-4ebd-b0db-f4e09fea9104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SDK: Form plugins</value>
      <webElementGuid>7a07695e-ac24-45f3-8d5f-37ba16f24d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/p[@class=&quot;multiple&quot;]/a[1]</value>
      <webElementGuid>a16f865b-484c-42e2-9659-bc653c5d0c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/div/div/div/p[4]/a</value>
      <webElementGuid>731454d6-092c-48ca-b9d9-48ea51c99ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SDK: Form plugins')]</value>
      <webElementGuid>79127baf-111a-47fc-9c9e-1ad870f751e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nintex Xtensions'])[1]/following::a[1]</value>
      <webElementGuid>664807e7-f8d6-4ec3-bf7b-dc85ab5188c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nintex Automation Cloud for Government'])[1]/following::a[2]</value>
      <webElementGuid>d117dfc9-007d-4048-a444-05e3bc2226b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDK: Nintex Automation Cloud API'])[1]/preceding::a[1]</value>
      <webElementGuid>47a42320-d798-4b63-b38a-87ba5f36a036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Discovery Support and Release Strategy'])[1]/preceding::a[2]</value>
      <webElementGuid>36cf19e2-682f-4003-8ff1-d4afe08df7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SDK: Form plugins']/parent::*</value>
      <webElementGuid>5c15a17d-4350-4e1d-8317-fc22932011f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://help.nintex.com/en-US/formplugins')]</value>
      <webElementGuid>eaaff470-58fe-4c6a-9077-eed3580c5f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>a2450fcc-9384-47d1-9c43-9ae2fa06f456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
