<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Case 00001063 was created</name>
   <tag></tag>
   <elementGuidId>28d91227-0741-47b3-a558-523cfd24586e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.toastMessage.slds-text-heading--small.forceActionsText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//*[@data-key='success']//a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(ends-with(text(), ' was created.') or ends-with(., ' was created.'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddbf005e-beea-472c-8c8f-3ac0023f21bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toastMessage slds-text-heading--small forceActionsText</value>
      <webElementGuid>5545e346-80db-418d-8ac2-d500b9b56e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>12972:0</value>
      <webElementGuid>d1b0667b-113b-4f6d-a909-b28c4e6832a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceActionsText</value>
      <webElementGuid>57dc0bd8-0ac9-44a6-987f-7e484092c114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>ends with</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> was created.</value>
      <webElementGuid>848663a8-d3c2-4e3a-ba6c-04bbe184c1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastDescription12959:0&quot;)/span[@class=&quot;toastMessage slds-text-heading--small forceActionsText&quot;]</value>
      <webElementGuid>98b9fabd-9f9a-4f87-a20f-4dafda8111c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='success'])[1]/following::span[1]</value>
      <webElementGuid>7a42d23c-9ccf-45b4-bf96-846bc9c7224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[4]/following::span[3]</value>
      <webElementGuid>e15d5ca9-a769-4340-b6c3-b9505b68d2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>4de69bf9-0366-4f70-8a9b-bff733be1c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'toastMessage slds-text-heading--small forceActionsText' and (text() = 'Case &quot;00001063&quot; was created.' or . = 'Case &quot;00001063&quot; was created.')]</value>
      <webElementGuid>dacf9015-c7ea-4bd9-8d16-7ca00848a35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription12959:0']/span</value>
      <webElementGuid>51dbd18e-d680-4510-87ba-d97a4196e529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/span</value>
      <webElementGuid>73e8063d-cc53-4f62-85f5-ab3c6a7b5037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
