<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-Mail Adresse_e_mail</name>
   <tag></tag>
   <elementGuidId>5a32f2f2-9779-4af6-b36c-022e181f86ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-e-mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-flexbox-02']/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-Mail Adresse&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b7d15c0-9358-463d-99a0-b94a052b55f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-required-error</name>
      <type>Main</type>
      <value>Dies ist ein Pflichtfeld.</value>
      <webElementGuid>4e1e8be7-a127-485c-bba1-bec2a1d0dc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-e-mail</value>
      <webElementGuid>96b924c6-5979-4a8d-980a-13c5603f45dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-maxlength</name>
      <type>Main</type>
      <value>E-Mail Adresse field has a maximum length of 254.</value>
      <webElementGuid>d56cef55-89c6-449f-af21-1a243b28d39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-email</name>
      <type>Main</type>
      <value>E-Mail Adresse ist nicht gültig.</value>
      <webElementGuid>77604fc8-c7ae-40e0-90f9-c6c42b60d3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Dies ist ein Pflichtfeld.</value>
      <webElementGuid>a79162d3-fbe7-44f1-86cd-64dabd12593c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>55529de3-f071-40b8-b63d-ae8fcb59399a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-e-mail</value>
      <webElementGuid>561ba66a-ebe5-49f6-9608-5347767969e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>e_mail</value>
      <webElementGuid>9b65c8de-c6e9-4228-979d-5dd697d69d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>d7c67e81-0bef-454f-b0a0-f9958461f209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>7328aa41-48da-489c-bb49-da30f2740a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-email required</value>
      <webElementGuid>28d0815f-3ffb-4688-8611-74bc7555fe07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f0673601-675f-495b-9234-bff9ecf0ca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8057401-ff7b-40bc-abf5-39ec6352b903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-required-error</value>
      <webElementGuid>46de6293-10a0-4763-aa5a-180b6098dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-e-mail&quot;)</value>
      <webElementGuid>7549a3f3-5372-4b57-a0b6-23329e3eb23f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-flexbox-02']/div/div[2]/div/input</value>
      <webElementGuid>72572519-ea26-47d3-b85b-142ce412bb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-e-mail']</value>
      <webElementGuid>c0ba2a48-fdb0-4e7e-a2b8-6f0d05385035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/input</value>
      <webElementGuid>52395bf4-6234-4fcb-891b-56bce001cf41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
