<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_consent_g_consent_g</name>
   <tag></tag>
   <elementGuidId>43eb2663-6b12-4908-9da3-5269bcb027c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-consent-g</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-flexbox-02']/div/div[7]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;consent_g&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdcd2d76-47f9-4682-8d7a-da7401f96dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-consent-g</value>
      <webElementGuid>9d0a2b3d-5523-4929-a8d9-afa69d874dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>edit-consent-g--description</value>
      <webElementGuid>2d461ad5-387d-4e0c-9944-b6357b6e4ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>12f140ea-cc7f-43ac-9924-42c78403638b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-consent-g</value>
      <webElementGuid>010e3439-220d-4711-bcee-3c306aee131e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>consent_g</value>
      <webElementGuid>f8631f53-0e43-465a-80eb-a5c65c6e9c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23d2734d-da5a-49ed-95cc-7e5022473f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox</value>
      <webElementGuid>2781723d-e9ff-4d21-ae7d-14b4080f35b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-states</name>
      <type>Main</type>
      <value>{&quot;disabled&quot;:{&quot;.webform-submission-newsletter-paragraph-45588-add-form :input[name=\u0022consent_d\u0022]&quot;:{&quot;unchecked&quot;:true}}}</value>
      <webElementGuid>f3299b16-8950-4702-a67a-7c16663f7e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-consent-g&quot;)</value>
      <webElementGuid>aa17aac5-9260-4829-b989-d3158320b5c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-flexbox-02']/div/div[7]/div/input</value>
      <webElementGuid>64ee1b6e-b07f-49a0-bd3b-95f8ccda5c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-consent-g']</value>
      <webElementGuid>5546114a-756d-4c40-8733-23e2bb43432b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>be7a245e-ca86-4bc0-a144-4da4a6ab225e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
