<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Einwilligung_consent_d</name>
   <tag></tag>
   <elementGuidId>30d4c82d-0bb4-4c76-a8df-0eaa2b255b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-consent-d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='edit-flexbox-02']/div/div[6]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Einwilligung&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>502af266-2dd2-4f82-ac96-2b38931a74e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-webform-required-error</name>
      <type>Main</type>
      <value>Ohne dein Einverständnis ist uns aus datenschutzrechtlichen Gründen eine Bearbeitung der Transaktion leider nicht möglich.</value>
      <webElementGuid>f1ce92af-579f-4d63-a2b0-bca75c15b6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-consent-d</value>
      <webElementGuid>3a00b8f3-29bf-44ab-bf0c-ae75182246ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>edit-consent-d--description</value>
      <webElementGuid>2bde926e-8e49-477d-9a43-12fb8a11f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Ohne dein Einverständnis ist uns aus datenschutzrechtlichen Gründen eine Bearbeitung der Transaktion leider nicht möglich.</value>
      <webElementGuid>9a4b08f9-7280-421d-aea1-3d994bedde2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b560cbde-0739-4ea3-9e13-ecc14a7bc177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-consent-d</value>
      <webElementGuid>d6bd16cd-57bd-4bc2-a6dd-10c384fefc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>consent_d</value>
      <webElementGuid>bb847c5b-ab2e-4c46-bae8-32012e31223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f7b7914-d47a-4516-959b-dfef4f79944f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox required</value>
      <webElementGuid>c4f41bd1-9414-4087-8ad9-9cd3acdb8610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>27142b12-53aa-40c1-a0b8-869f0ed6863b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15c080e3-7f23-4acd-b49c-2ab4bdfaf23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-once</name>
      <type>Main</type>
      <value>webform-required-error</value>
      <webElementGuid>cff00cbe-7f88-4472-9169-89e63e48d6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-consent-d&quot;)</value>
      <webElementGuid>3b83f27c-57cc-4fa8-9399-e8c858ae75eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='edit-flexbox-02']/div/div[6]/div/input</value>
      <webElementGuid>9d22b5a3-d43c-4a16-8bbb-2f733890f5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-consent-d']</value>
      <webElementGuid>90b423ff-aac2-4bd7-96cb-be3983dca251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>55008c9a-cbef-48f8-a730-53551ba6c943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
