<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ADVENTUROS</name>
   <tag></tag>
   <elementGuidId>77635c0e-2c4b-4180-a582-25ed5af0ca2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image-label--adventuros.js-form-item.form-item.js-form-type-checkbox.form-type-checkbox.js-form-item-dog-brand-adventuros.form-item-dog-brand-adventuros > label.option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-dog-brand']/div[4]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ADVENTUROS&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>130fc930-83e1-4c47-8287-6aefd2c0730a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>edit-dog-brand-adventuros</value>
      <webElementGuid>8ed477cd-58db-4118-af77-8d8780c8013c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9235f44b-724c-4d1e-8ee2-d3929b05fc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADVENTUROS</value>
      <webElementGuid>019b1d9d-92ec-4457-9165-f3b67d1a71d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-dog-brand&quot;)/div[@class=&quot;image-label--adventuros js-form-item form-item js-form-type-checkbox form-type-checkbox js-form-item-dog-brand-adventuros form-item-dog-brand-adventuros&quot;]/label[@class=&quot;option&quot;]</value>
      <webElementGuid>fcaa5fda-235e-4036-9b76-d00f5d12ad37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-dog-brand']/div[4]/label</value>
      <webElementGuid>83b17fed-b240-440c-aa9a-4df48c35d5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRO PLAN HUND'])[1]/following::label[1]</value>
      <webElementGuid>6d36b8b5-edb1-46d5-837a-5cc0ea135291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PURINA ONE DOG MINI'])[1]/following::label[2]</value>
      <webElementGuid>c48476b4-d64d-484e-8880-9b8dbade43b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DENTALIFE'])[2]/preceding::label[1]</value>
      <webElementGuid>d9298b54-d50c-44c0-96ff-3d725dba5cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WELPENSCHULE'])[1]/preceding::label[2]</value>
      <webElementGuid>83d428a6-549e-479e-915b-a13ce2903384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADVENTUROS']/parent::*</value>
      <webElementGuid>0b65f9a6-a9a6-450f-8bfe-27f44990ae2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div[4]/label</value>
      <webElementGuid>c14fa48f-9e72-43a0-ab5c-d42fdc2b99b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
